### ISSUE TITLE
How to get all customer subscriptions?

### ISSUE THREAD

**Issue by artemaliinyk** [stripe/stripe-php#1000]
### **Hey. I need a piece of advice. I need to get all customer subscriptions.** 
**Any status. Any subscriptions. During all time. Absolutely all subscriptions of the client. Who has the status (active, canceled, etc.).** 

It is in your describes documentation that this is easy to do - https://stripe.com/docs/api/subscriptions/list

I do the same.

`Stripe\Subscription::all([status' => 'all', 'customer' => 'id']);`

**But I always get one customer subscription.**

Two photos show ****two** customer subscriptions** (active and canceled).

![image](https://user-images.githubusercontent.com/62883928/90827206-85c84f80-e344-11ea-88b7-a42262ed1b32.png)

![image](https://user-images.githubusercontent.com/62883928/90827221-8cef5d80-e344-11ea-83ee-cd4686d8f546.png)

As a result, I get only ****one** customer subscription**. (`Stripe\Subscription::all([status' => 'all', 'customer' => 'id']);`)

![image](https://user-images.githubusercontent.com/62883928/90827407-dcce2480-e344-11ea-8dd6-2048b8045531.png)

Please, I need some advice on how to get all the subscriptions of a client he had.

I'm using version - `"stripe/stripe-php": "~v6.9.0"`.

Let me remind you that I am trying to get all the client's subscriptions this way:

 `$subscriptions = Stripe\Subscription::all(['status' => 'all', 'customer' => 'cus_id']);`

 ### Looking forward to your reply. Thanks for your service Stripe.

**Comment by remi-stripe** [comment]
@artemaliinyk Flagging that Github issues should be limited to bugs with the library itself and not questions about our product so I'm going to close this out.

To unblock you though, this issue usually happens when your account is on an old API version from a time where we did not return canceled subscriptions. Before [2016-07-06](https://stripe.com/docs/upgrades#2016-07-06), we didn't return the canceled subscriptions though passing `all` should work.

Looking into the account associated with the customer id you mentioned, the API version is correct and the JSON output you shared is for a customer that only has one Subscription total that was cancel. As far as I can tell, the API is working fine and I've also confirmed on my own account. I'd recommend triple-checking the customer id(s) you are passing in each API call and that they match what you would expect.

If you are still blocked after that, I'd recommend asking our support team and providing them with detailed examples so that they can look into this for you
