### ISSUE TITLE
InvoiceItem::delete($invoiceItem->id) does not work

### ISSUE THREAD

**Issue by MathiasLund** [stripe/stripe-php#1013]
Hey there,

I am using stripe-php library version 7.0, and I am trying to delete an invoiceItem programatically.

However, I cannot get it to work using the `InvoiceItem::delete($invoiceItem->id)` command.

It fails with exception: 

`You must pass an array as the first argument to Stripe API method calls.  (HINT: an example call to create a charge would be: "Stripe\Charge::create(['amount' => 100, 'currency' => 'usd', 'source' => 'tok_1234'])")`

Am I missing something, or is this a bug?

**Comment by remi-stripe** [comment]
@MathiasLund When you use the old access pattern, you have to retrieve first and then call delete like this:

```
$item = \Stripe\InvoiceItem::retrieve('ii_123');
$item->delete();
```

Since that makes an extra request, we recently introduced a new client/service approved in 7.33.0 documented [here](https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0) which makes things easier as you can call delete directly as documented in our API reference [here](https://stripe.com/docs/api/invoiceitems/delete?lang=php):

```
$stripe = new \Stripe\StripeClient('sk_test_123');
$stripe->invoiceItems->delete(
  'ii_123',
  []
);
```
