### ISSUE TITLE
Abnormally long time to retrieve all invoices (around 40 seconds)

### ISSUE THREAD

**Issue by bastien70** [stripe/stripe-php#1032]
Hello, in my application, I have to retrieve all the invoices based on a start and end date.

So I proceed as follows:

```php
$invoices = \Stripe\Invoice::all([
            'created' => [
                'gte' => strtotime($begin),
                'lte' => strtotime($end),
            ],
        ]);

        $iterator = $invoices->autoPagingIterator();
```

But I noticed that this call cost me almost 40 seconds to process!

I tested without the settings to see, but same thing.

There seems to be a big problem with this call

**Comment by ChuVienTran** [comment]
Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: bastien70 <notifications@github.com>
Đã gửi: Thursday, October 22, 2020 11:25:19 PM
Đến: stripe/stripe-php <stripe-php@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Chủ đề: [stripe/stripe-php] Abnormally long time to retrieve all invoices (around 40 seconds) (#1032)


Hello, in my application, I have to retrieve all the invoices based on a start and end date.

So I proceed as follows:

$invoices = \Stripe\Invoice::all([
            'created' => [
                'gte' => strtotime($begin),
                'lte' => strtotime($end),
            ],
        ]);

        $iterator = $invoices->autoPagingIterator();

But I noticed that this call cost me almost 40 seconds to process!

I tested without the settings to see, but same thing.

There seems to be a big problem with this call

**Comment by remi-stripe** [comment]
@bastien70 When you use one of our List APIs, you will render a lot of objects and paginate through them all. Depending on the number of invoices you have, you could paginate through hundreds (or even millions) of objects. When you paginate, you get a default page of 10 items (which you can tweak via the `limit` parameter between 1 and 100). Then when you use `autoPagingIterator` you will go through each element and whenever you reach the end of a page it will automatically fetch the next 10 one, repeatedly until you get through all the pages. It's expected that paginating through all objects will take some time to complete.

Since this is more a product/API question and is not a problem with the stripe-php library itself, I'm going to close this issue, I hope it's okay. I recommend reaching out to our support team and providing more details about your current call(s) and the number of invoices you are paginating through. They can help you out here: https://support.stripe.com/contact
