### ISSUE TITLE
Identity support?

### ISSUE THREAD

**Issue by adamevers** [stripe/stripe-php#1037]
I'm curious if you're planning on building in support for the Identity product? 

I would assume something like this would work in the future? 

```
$identity = $stripe->identity->verificationIntents([
    'return_url' => 'https://example.com/return?vi={VERIFICATION_INTENT_ID}',
    'requested_verifications' => ['selfie'],
	'metadata' => ['email' => 'you@email.com']
]);
```

**Comment by remi-stripe** [comment]
@adamevers The product is in beta at the moment which is why it's not in our client libraries like stripe-php. During a beta, we sometimes iterate a lot on the API design based on user feedback and those can cause confusion or breaking changes in client libraries if we add support too early.

For example while the API is called `VerificationIntent` right now, we're re-designing it to be called `VerificationSession` in the future. If we had shipped this early, you'd have both classes in stripe-php but one would be deprecated and cause tech debt.

As soon as the API is ready to be released publicly though all our libraries will support the product!
