### ISSUE TITLE
Passing $opts['api_key'] to OAuth::deauthorize has no effect

### ISSUE THREAD

**Issue by jellyNoone** [stripe/stripe-php#1042]
Hi, I'm trying to use OAuth and am currently passing the api_key per every request rather than using the Stripe::setApiKey or the StripeClient. I was under the impression that you can pass the api_key through the $opts parameter. However this does not seem to be possible for the \Stripe\OAuth::deauthorize method and looking at the source probably also for the \Stripe\OAuth::token method. Was I in the wrong for thinking api_key should have an effect here?

**Comment by remi-stripe** [comment]
@jellyNoone Thanks for reaching out! You're correct that the OAuth methods don't support passing a custom API key in `$opts`. It's due to a bug in the past and fixing it could break existing users that incorrectly pass an API key and would require a major version change.

A few months ago, we shipped a new infrastructure for the stripe-php library which uses client/services. This is documented in more details here: https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0

Since that approach was new, we were able to fix this issue in the new path. If you start using a client, you can now pass a custom API key when you make the calls to `token` or `disconnect`. Here's what it looks like:

```
$stripe = new \Stripe\StripeClient([
  'api_key' => 'bad_key_that_does_not_exist',
  'stripe_version' => '2020-08-27',
]);

$response = $stripe->oauth->token([
  'grant_type' => 'authorization_code',
  'code' => 'ac_12345',
],
[
  'api_key' => 'sk_test_12345',
]);
```

This code works (I just confirmed locally) and should allow you to continue passing an API key per-request even for the OAuth calls. You can migrate just the OAuth calls for now, though I'd encourage you to migrate all your calls to the new approach as it has a lot of benefits, such as allowing you to make static calls for all methods which doesn't require fetching an object to delete it for example.

Let me know if that doesn't help!

**Comment by jellyNoone** [comment]
I just posted another issue regarding the StripeClient #1043 . Thank you, I will migrate to using the StripeClient.
