### ISSUE TITLE
Tax missing in prorated subscription

### ISSUE THREAD

**Issue by jmbianca** [stripe/stripe-php#1067]
Hello,

I want to make prorated subscription until the next month for **new** subscribers. I have a tax defined in Stripe, and everything thing works fine WITHOUT proration. But, if I had a _'billing_cycle_anchor'_ to have a prorated subscription, the tax is missing in the subscription and in the invoice. Here my code:
```
$subscription = $stripe->subscriptions->create(
                [
                    'customer' => 'cus_...',
                    'items' => [
                        [
                            'price' => 'price_1Hdxo...',
                            'tax_rates' => [
                                'txr_1Hdxr4GEy...',
                            ],
                        ],
                    ],
                    'expand' => ['latest_invoice.payment_intent'],
                    'billing_cycle_anchor' => $next_payment_timestamp,
                ]
            );
```
The only difference is removing the last line, and the tax come back. 
Any ideas?

**Comment by remi-stripe** [comment]
@jmbianca Thanks for reaching out. Github issues should be limited to bugs with the stripe-php library itself. This question is more about the product itself and why tax is not added on proration (which is expected behaviour today).

I'd recommend reaching out to our support team directly instead: https://support.stripe.com/contact and they can help you look into this if you provide specific examples from your account.
