### ISSUE TITLE
Unknow parameter name in stripe api

### ISSUE THREAD

**Issue by mohammadwais** [stripe/stripe-php#1068]
before 12 oct  2020 

POST  /v1/plans

parameter

{
  "amount": "1000",
  "interval": "day",
  "name": "Gold",
  "currency": "usd",
  "id": "gold"
}
working fine 

but now this api giving me error 

Received unknown parameter: name

**Comment by remi-stripe** [comment]
@mohammadwais Github issues should be limited to bugs with the stripe-php library itself. This question is more an integration question about why your code breaks. We recommend that you reach out to our support team instead for help: https://support.stripe.com/contact

To unblock you though the `name` parameter on the Create Plan API has been removed multiple years ago in the API version [2018-02-05](https://stripe.com/docs/upgrades#2018-02-05) when we introduced the `Product` API resource. Your code would work fine if you use an API version before that but it will fail otherwise since the parameter does not exist anymore for earlier versions of the API.

If you have any follow up questions, our support team will be best equipped to help!
