### ISSUE TITLE
Subscription cancellation?

### ISSUE THREAD

**Issue by shez1983** [stripe/stripe-php#1072]
So for creating or updating i can simply do 
```
 \Stripe\Subscription::update  or create
```
but for cancel i think the code is wrong? for example if i follow the path/func called there is no way to set the ID, in one of the old project where we dont use composer, I have 'updated' the lib code to use same code as your update but in one of the newer projects, i am not sure whats the best way?  (cancel is also not a static method like update/create are, update asks for an id as first param, cancel doesnt so the instance URL is probably wrong as it should have an id,  i have tried passing 
```
->cancel(['id' => 'subscription_id']);  
```
but this returns an error from stripe

**Comment by paulasjes-stripe** [comment]
This isn't a bug with the stripe-php library so I'm closing this. In the future if you are having integration issues it's best to contact Stripe support directly at https://support.stripe.com/contact

To unblock you however, since you are using the legacy static method approach, you can just call `cancel` on the subscription object itself:

```
// Create the subscription
$subscription = \Stripe\Subscription::create([
    'customer' => 'cus_123',
    'items' => [
        [
            'price' => 'price_123,
            'quantity' => 1,
        ],
    ],
]);

// Cancel the subscription
$subscription->cancel();
```
