### ISSUE TITLE
PHP version 5.5.9

### ISSUE THREAD

**Issue by Studiodews** [stripe/stripe-php#1073]
I use php version 5.5.9, please what version of the stripe library should I use and how best can I initialize it.

**Comment by paulasjes-stripe** [comment]
Closing this as this isn't an issue or bug report for the stripe-php library.

If you need help with your Stripe integration, I suggest reaching out to Stripe support instead at https://support.stripe.com/contact

To unblock you, stripe-php stopped supporting PHP version 5.5.9 since v7, meaning that the latest version of stripe-php you can use is [v6.43.1](https://github.com/stripe/stripe-php/tree/v6.43.1).

Bear in mind that if you are using that version you will not have access to features introduced since then. Since PHP 5.5.9 reached [end of life status in January 2019](https://www.php.net/supported-versions.php), I strongly recommend you upgrade.
