### ISSUE TITLE
After Successful charge using payment intent unable to transfer amount "source_transaction" => intent_id

### ISSUE THREAD

**Issue by niraj-lal-rahi** [stripe/stripe-php#1074]
Unable to transfer amount using intent id

        $intent = \Stripe\PaymentIntent::create([
                'amount' => $amount * 100,
                'currency' => opt('payment-settings.currency_code'),
                'customer' => $customer,
                'payment_method' => $pm_id,
                'off_session' => true,
                'confirm' => true,
            ]);
            
         $transfer = \Stripe\Transfer::create([
                 "amount" => $creator_amount*100,
             "currency" =>  opt('payment-settings.currency_code'),
            "source_transaction" => $intent['id'],
         "destination" => $seller_id['account_id'] , //connected user account id whose product purchased by buyer
    
       ]);

**Comment by remi-stripe** [comment]
@niraj-lal-rahi This is a question about your code and not an issue about the library so we recommend talking to our support team directly: https://support.stripe.com/contact

To unblock you though, the issue is that `source_transaction` expects a **Charge id** (ch_123) instead. So you want to pass `$intent->charges->data[0]->id` instead, assuming the charge creation did succeed.
