### ISSUE TITLE
Discount or coupon on first payment of Subscription

### ISSUE THREAD

**Issue by pu3antasyah** [stripe/stripe-php#1084]
Payment pirce is recurring anually.

I'm using this lib with Codeigniter, Codexworld tutorial.

Currently this code working (without Coupon and Discount).

How to apply discount or coupon on first payment of this Subscription price?

```
$customer = $this->stripe_lib->addCustomer($email, $token);
if($customer){
  $subscription = $this->stripe_lib->createSubscription($customer->id, $priceID);
    if($subscription){
        $invoiceObj = $this->stripe_lib->getInvoice($subscription->latest_invoice);
        //----- NEXT >>>>>>
    }
}
```

**Comment by remi-stripe** [comment]
@pu3antasyah thanks for reaching out. Github issues are limited to bugs and feature requests in the library itself. For product questions you should talk to our support team instead: https://support.stripe.com/contact

I want to give you some pointers to unblock you but your question is more about a third-party plugin/code. I looked around and I'm guessing you are looking at [this tutorial](https://www.codexworld.com/stripe-subscription-payment-integration-in-codeigniter/). If so you can see that the `createSubscription` method is not really a Stripe method, it's part of the tutorial. And it looks like this

```
function createSubscription($customerID, $planID){ 
  try { 
    // Creates a new subscription 
    $subscription = \Stripe\Subscription::create(array( 
      "customer" => $customerID, 
      "items" => array( 
        array( 
          "plan" => $planID 
        ), 
      ), 
    )); 
      
    // Retrieve charge details 
    $subsData = $subscription->jsonSerialize(); 
    return $subsData; 
  }catch(Exception $e) { 
    $this->api_error = $e->getMessage(); 
    return false; 
  } 
} 
```

That method doesn't take another argument for a coupon id but you can easily change it (since it's your code) to support it. And then that coupon id can be passed to the subscription creation call. You'd have something like this:

```
function createSubscription($customerID, $planID, $couponID){ 
  try { 
    // Creates a new subscription 
    $subscription = \Stripe\Subscription::create(array( 
      "customer" => $customerID, 
      "coupon" => $couponID,
      "items" => array( 
        array( 
          "plan" => $planID 
        ), 
      ), 
    )); 
      
    // Retrieve charge details 
    $subsData = $subscription->jsonSerialize(); 
    return $subsData; 
  }catch(Exception $e) { 
    $this->api_error = $e->getMessage(); 
    return false; 
  } 
} 
```

You can read more about Subscriptions and discounts here: https://stripe.com/docs/billing/subscriptions/discounts

I won't be able to answer more questions here as it's a support question but our support team can help if you need more details!
