### ISSUE TITLE
Why is stripe payment intent response inside another array at "charges->data" 

### ISSUE THREAD

**Issue by mountwo23** [stripe/stripe-php#1097]
Im trying to get the charge id from a payment intent but I dont understand why there is another array inside an array.

Im not having any problems with getting the charge id but i have to do it like this
$intent->charges->data[0]["id"];
And i think it should just be like this
$intent->charges->data->id;

If you check the api document on the website for payment intent
u will see that the data attribute has an empty array and when it does have data after payment, it has a single array inside it.

Thanks

**Comment by remi-stripe** [comment]
@mountwo23 The `charges` property is what we call a sub-list in the API. It can contain multiple objects. There are many examples in our API such as `line_items` on `Session` or `refunds` on `Charge`. On `PaymentIntent`, the list can only contain one element for performance reasons but it follows the same pattern as other sub-lists which is why it's an array.

Since this isn't really an issue with the library itself, I'm going to close this out but don't hesitate to reach out to our support team if you have any follow up questions: https://support.stripe.com/contact
