### ISSUE TITLE
Feature Request: improve API when modifying invoices

### ISSUE THREAD

**Issue by pbreah** [stripe/stripe-php#1105]
This is a feature request for the stripe API, because it seems to be like "all or nothing" to add a simple memo field to an invoice.

I am aware of the API method that updates the description field

```
\Stripe\Invoice::update('in_XXX', [ fields_I_want_to_update ])
```

I heard and read on the docs that invoices take around 1 hour be sent to the customer and around that period of time it is possible to update the invoice. I did within the same minute the transaction was initiated but got: "Finalized invoices can't be updated in this way". Even on my use case, I don't want to delay the invoice that much, just to do a small change to the invoice after a successful payment & subscription, then send the invoice immediately after that.

Then there is the hack suggested to someone on #freenode to set a trial period in the future for a few seconds so it forces the invoice to be sent around 1 hour. To give time to update the invoice.

Then there is the "auto_advance" set to false. But all the needed automatic workflow is set to manual, and now I have to write much more code to handle everything by hand.

I would love to see a way that I can keep the auto_advance to true, and have an intermediate mode to just wait for me to do a last minute update to the invoice before sending it to the customer, then continue with all stripe does with auto_advance set to true. Because I want the invoice to be sent immediately to the customer (a few minutes after the transaction) but still be able to modify the invoice via the api to add a memo or description to it.

Hope this description is clear, and the Stripe team can talk about making this easier. I think this is something that can be improved for simpler integrations. 

Also thanks for all the great work the Stripe team does, amazing work guys!

**Comment by remi-stripe** [comment]
@pbreah Finalized invoices can not be updated or mutated for compliance reasons in many countries which is why the API blocks this. You have to make this change before the invoice is charged, it's too late to do it afterwards. This is a hard requirement and not something we would lift though so you will need to plan the change ahead of the payment attempting using some of the workarounds you mentioned. It has to always be done before the payment.

This is more a feature request about the product itself though and not a limitation of the stripe-php library. Github issues should be limited to issues with the library itself so I'm going to close this out. You should make sure to raise that feedback with our support team directly instead: https://support.stripe.com/contact
