### ISSUE TITLE
Metadata not being returned when querying for all plans i.e. Plans::all()

### ISSUE THREAD

**Issue by nagra** [stripe/stripe-php#1112]
Hey all 👋,

First time posting here, so I apologise in advance if my request is not formatted as expected 🙏.

#### Issue Description:
I'm using the following bit of code to retrieve all the plans added to my Stripe account (test data mode):

```
\Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));
$plans = \Stripe\Plan::all();
``` 

The plans are returned as expected, however the `metadata` I added in the dashboard seems to be missing.
I double checked the response using an API client, and the `metadata` is successfully returned on the client. 

#### Expected
All plans are returned including the `metadata`.

#### Actual
All plans are returned **not** including the `metadata`.

#### Details
Laravel Cashier Version: `12.7`
Stripe Version: `7.39`
PHP Version: `8.0.1`

Thank you.

**Comment by remi-stripe** [comment]
@nagra Hello! This is unlikely to be a problem with the stripe-php library and more likely that the metadata you set up was on the Product itself for example. I would recommend contacting our support team instead directly and providing some example Plans you're looking at so that they can help you debug this: https://support.stripe.com/contact
