### ISSUE TITLE
Any ETA concerning StripeQuote availability?

### ISSUE THREAD

**Issue by webda2l** [stripe/stripe-php#1114]
Hello,

Even if it's in a beta, it will be welcome to have its code, in a `beta` branch maybe?

Thanks.

**Comment by remi-stripe** [comment]
@webda2l At the moment we do not support beta features in client libraries unfortunately so there wouldn't be a beta branch/release. The Quotes API would only be added once we're ready to release it publicly for everyone. We don't have a firm date for release just yet unfortunately but it's likely a few months out at least.

I'm going to close this out since the feature will automatically be in stripe-php (and other client libraries) once it ships publicly!

**Comment by webda2l** [comment]
Ok thanks anyway!

**Comment by webda2l** [comment]
Close by https://github.com/stripe/stripe-php/pull/1152, thanks
