### ISSUE TITLE
issue on token 

### ISSUE THREAD

**Issue by suhan-gajjar** [stripe/stripe-php#1132]
I am creating a plugin for WordPress using this library for multiple stripe account and I am facing an issue in the token. I am trying to pass the 3d card and it is not generating a token for this card as it takes 4242 cards for payment by defualt.

Please help me where I am doing wrong the code is below i am used
```
$payDetails = \Stripe\Charge::create(array(
            'customer' => $customer->id,
            'amount'   => $itemPrice,
            'currency' => $currency,
            'description' => $itemName,
            'metadata' => array(
                'order_id' => $orderID
            )
        ));
        $payment_source = array(
            'card_id'   => $payDetails->source['id'],
            'object'   => $payDetails->source['object'],
            'customer'  => $payDetails->source['customer'],
            'brand'  => $payDetails->source['brand'],
            'exp_month'  => $payDetails->source['exp_month'],
            'exp_year'  => $payDetails->source['exp_year'],
            'last4'     => $payDetails->source['last4'],
            'fingerprint'  => $payDetails->source['fingerprint'],
            'funding'  => $payDetails->source['funding'],
        );
        $saved_user_data = array(
            'ch_id'   => $payDetails->id,
            'customer_id'   => $payDetails->customer,
            'payment_method'  => $payDetails->payment_method,
            'payment_source'  => $payment_source,
        );
```

**Comment by paulasjes-stripe** [comment]
Issues should be limited to bugs with the library itself rather than integration issues. Please reach out to Stripe support directly in the future for help with your integration: https://support.stripe.com/contact

To unblock you, the Charge API doesn't work with 3DS enabled cards. Instead you need to use the PaymentIntents API. See the docs on how to migrate here: https://stripe.com/docs/payments/payment-intents/migration
