### ISSUE TITLE
Deleting price support

### ISSUE THREAD

**Issue by bastien70** [stripe/stripe-php#1150]
Hello,

It would be nice to implement the ability to remove a price.

From the dashboard stripe, we can, which calls a "**DELETE**" method, which returns this:

```json
{
  "id": "price_1J8QvjGgCQgXBLKXhUrhVm0j",
  "object": "price",
  "deleted": true
}
```

We do not currently have the opportunity to do :

```php
$stripe->prices->delete('price_id');
```

And we can't go through updating a price to do this because we can't modify the '**deleted**' property ourselves.

Could you add this possibility to the library?

**Comment by remi-stripe** [comment]
@bastien70 The reason it's not in the libraries is because the API just doesn't support this. Only the Dashboard can do it, for compatibility reasons with the legacy Plan API. We don't have plans to support Price deletion further as we discourage deleting objects in general and you should instead switch to `active: false`.
