### ISSUE TITLE
Fatal error:  Uncaught (Status 400) (Request re) You cannot add cards or bank accounts for payouts and top-ups away from the dashboard. 

### ISSUE THREAD

**Issue by ajayreddy01** [stripe/stripe-php#1165]
Unable to add  external cards and bank accounts using Api
`<?php 
require('../../core/api/config.php');
\Stripe\Stripe::setVerifySslCerts(false);

$bank_token = 'btok_1....';//token generated using stripe.js api

$data =$stripe_all->accounts->createExternalAccount(
    "$acoount",
    [
        "external_account" => $bank_token,
    ]
);
print_r($data);
?>`

**Comment by paulasjes-stripe** [comment]
Please only create issues for this repo if it's a bug or problem with the stripe-php repo specifically. For integration questions you should reach out to Stripe support directly: https://support.stripe.com/contact

To unblock you, you cannot add cards or external bank accounts for payouts for your own account via the API. This endpoint is for adding those for connected accounts.

If you meant to add an external bank account for a connected account, please double check that `$acoount` references that connect account ID rather than your own.
