### ISSUE TITLE
getting promocode relegated product

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [stripe/stripe-php#1180]
I want to get promocode related product  (applies_to)
like 
```
StripeCoupon::retrieve($request->promo_code, ["expand" => ["data.coupon.applies_to"]])
```

**Comment by remi-stripe** [comment]
@MoatazAbdAlmageed Github issues should be limited to bugs with the library itself. Your ask is more a feature request/integration question which would be better directed to our support team: https://support.stripe.com/contact

We do not support retrieving a Coupon from a PromotionCode today since they are different resources. We expect the coupon id as the first parameter. If you have the PromotionCode id, you can call the Retrieve Promotion Code [API](https://stripe.com/docs/api/promotion_codes/retrieve) which returns the `Coupon` object in it and you can expand the `applies_to` hash at the same time:

```
$stripe->promotionCodes->retrieve(
  'promo_123',
  [
    'expand' => ['coupon.applies_to'],
  ]
);
```

Hope this unblocks you but for further questions please talk to our support team for help: https://support.stripe.com/contact
