### ISSUE TITLE
Subscription's Update method is missing in library

### ISSUE THREAD

**Issue by shayan-izadi** [stripe/stripe-php#1287]
### Is your feature request related to a problem? Please describe.

Hello everyone. It's my first time that I am working with this library and in my website we use subscription method.
When I want to cancel a subscription I use cancel method in _/lib/Subscription.php_ 
But I also want to allow user to update days of their payments means that change "interval_count" in stripe records but I found update method for subscription has not been defined in this library.

### Describe the solution you'd like

I think a simple update method should be added to  _/lib/Subscription.php_ like cancel method.

### Additional context

If you think there is a way to update "interval_count" of existing subscription with even this version of library I'll be thankful that you mentioned it here for me.

**Comment by remi-stripe** [comment]
@shayan-izadi Our library supports all public API methods documented in our reference and that includes every create or update method. You don't see it directly in `Subscription.php` because the update method is automatically included from [this code](https://github.com/stripe/stripe-php/blob/master/lib/Subscription.php#L61): `use ApiOperations\Update;`. You can also confirm it quickly by simply trying to call that method which would definitely work!

I also want to flag that you can't change `interval_count` as that doesn't exist on the `Subscription` resource. I'd recommend talking to our support team for help instead: https://support.stripe.com/contact
