### ISSUE TITLE
Ship experimental-v2

### ISSUE THREAD

**Issue by bkrausz** [stripe/stripe-php#134]
Any other features you'd like to see in v2? I have some changes to make to the way we persist header use, was thinking of just making them in v2 and shipping it this week.

Thoughts? @chadicus @kyleconroy @alexbilbie @jacksonj04 @bakura10 

I think the main thing is ability to instantiate a Stripe instance, which can be done additively.

**Comment by kyleconroy** [comment]
Since we need to make the breaking change for the Account resource, let's do it.

**Comment by bakura10** [comment]
I haven't check the code, I will stick with my ZfrStripe as I still find it much better (not only because I've made it :)). A few things that is nice to have (maybe you could do it as it's a very useful feature) is iterator. Basically, in ZfrStripe, I can do this:

```php
$customersIterator = $stripeClient->getCustomersIterator();

foreach ($customersIterator as $customer) {

}
```

And ZfrStripe takes care of sending the second request, and so on, until "has_more" is false. In a lot of cases this is really really handy ;).

**Comment by bkrausz** [comment]
Haha, yes I'm very happy to have ZfrStripe as an alternative :). CCed you since I figured you'd have good insight on features we may want to adopt.

auto-pagination is something I'd want to decide consistent if we want to support across all bindings: it's a good idea! I'll bring it up with the team. I think we'd make it an explicit call (like you did in your example) so that people can control whether or not we issue more blocking API calls.

I'm going to work on this over the next day or two, let me know if you have any other suggestions for features (and thanks again for all the hard work on ZfrStripe).
