### ISSUE TITLE
Subscription description not being applied when creating a checkout session

### ISSUE THREAD

**Issue by GoranPopovic1** [stripe/stripe-php#1367]
### Describe the bug

I am trying to create a checkout session and provide description for a subscription. I am setting these descriptions via subscription_data.description param. Seems similar issue is mentioned here for the node library: https://github.com/stripe/stripe-node/issues/1418

### To Reproduce

1. Create a checkout session: \Stripe\Checkout\Session::create();
2. Provide subscription_data with a description param: 

```
'subscription_data' => [
   'description' => 'Subscription Description',
],
```

3. The subscription description remains unchanged on the hosted checkout page, the description of the Stripe product is there by default.

### Expected behavior

Expecting to set a description for subscription type payments on the checkout session.

### OS

Windows

### PHP version

8.0

### Library version

v7.128.0

### API version

 2020-08-27

**Comment by nemanja9884** [comment]
I have exactly same problem.

**Comment by milosgacanovic** [comment]
Me too, i hope this gets fixed soon.

**Comment by Trick-Coin** [comment]
Same here. Would love to give my consumers a unique description tailored to their needs.

**Comment by remi-stripe** [comment]
Hello everyone! Github issues are limited to bugs with the library (stripe-php) itself. This question is not really about the library and more about the Checkout product so this isn't the right place to report this.

To help answer though, this is not a bug and is currently expected behaviour. The description was introduced more for distinguishing 2 Subscriptions to the same Product in the Customer Portal for example. Similarly to `payment_intent_data[description]` it's not something we show on Checkout today.

I do agree that it could make sense to show this on Checkout though and I'll flag to our product team. I recommend that you reach out to our support team to discuss this and raise your interest for this as a feature request: https://support.stripe.com/contact
