### ISSUE TITLE
Create customer with costume id (from other Stripe account)

### ISSUE THREAD

**Issue by kefahB** [stripe/stripe-php#1416]
### Is your feature request related to a problem? Please describe.

Hello,

First of all Happy new year :)

I am facing a problem about my business model, I have a smartphone application that we operate in Europe, and since a while we will expand ours business into UAE.

To avoid currency conversions, Stripe team advise us to create a brand new account for UAE with the locale currency `AED` and here start the issue.

I will explain how we currently does for each registered user:
- When a new user registered we create a new Stripe customer via this SDK
- the we store the customer ID into the DB
- we use the customer id from the DB to generate a ephemeral key and create a payment intent

Now the problem since we are about lunching the app in UAE with the UAE account (other credentials from the Europe account) when we try to use the customer ID to generate the ephemeral key or create a payment intent I says `No such customer` and that is true because the customer is created for the Europe account not for UAE!

But in the scenario that a user leave in France and he use the APP there, it work because we are able to get the customer ID, but in the case of the user traveling to UAE, and try to buy some think from there we will not find the customer because it is not registered on UAE account.

### Describe the solution you'd like

I do suggest to add a new option to the create a user API withe a customer ID, that we can keep the same customer ID across all account.

Ideally it could be a duplicate or clone customer from account to another but I did understand that it is a bit more complcated due to the data protections...

### Describe alternatives you've considered

```php

$this->stripe->customers->create([
        "customer_id" => 'cu_2ddZGHK88'
        "email" => $email,
        "name" => $name,
        "phone" => $phone,
        "address" => [],
        "metadata" => $metadata
    ],
    ["stripe_version" => self::API_VERSION]);
```

**Comment by richardm-stripe** [comment]
Hello @kefahB,

The github repository here is for bug reports and requests for the stripe-php library itself. It seems like your inquiry is more of a question about your integration and the Stripe API itself, and the support team at https://support.stripe.com/contact will be better equipped to help you. Please open a ticket there with your inquiry. I will close the issue here.

I did find [this docs page](https://stripe.com/docs/connect/cloning-customers-across-accounts) about how to use a Connect platform to clone customers across Stripe accounts, so perhaps you can start there?
