### ISSUE TITLE
HTML phpDoc not working in VSCode

### ISSUE THREAD

**Issue by FedericoBiccheddu** [stripe/stripe-php#1485]
### Describe the bug

In #1482 I started updating phpDocs to markdown. For example, in `VSCode` HTML is not rendered resulting in, sometimes, useless docs.

![stripe-phpdoc](https://user-images.githubusercontent.com/433819/234554467-b43d2129-caf4-4305-993f-ee34118fdf43.jpg)

Converting them in Markdown fixes the issue.

### To Reproduce

Hover to any prop that has some HTML.

### Expected behavior

Code, links and other info are correctly shown while hovering properties/classes.

![stripe-phpdoc-fixed](https://user-images.githubusercontent.com/433819/234555295-f39be253-2f81-4856-85bc-add1da440805.jpg)

### OS

Ubuntu

### PHP version

PHP 8.*

### Library version

stripe-php v10.12

### API version

2022-11-15

### Additional context

VSCode v1.77.3

**Comment by richardm-stripe** [comment]
Thank you! I'll take a look. Need to make sure markdown renders properly in PHPStorm too, as that is another popular IDE, but I will try and get the investigation/generator change done soon!

**Comment by pakrym-stripe** [comment]
I looked into this. The reason link didn't work was because they were split across multiple doc comment lines. https://github.com/stripe/stripe-php/pull/1499 merged those lines back.

Tested using PHPStorm and [PHP Intelephense  ](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)
