### ISSUE TITLE
Payment intent cancel create glitch

### ISSUE THREAD

**Issue by brijesh-bacancy** [stripe/stripe-php#1495]
### Describe the bug

When we try to cancel payment intent in "require_action" case, it return 500 error and log shows, as below.

Exception: Using $this when not in object context ..\application\libraries\stripe_lib\stripe\stripe-php\lib\PaymentIntent.php 60

### To Reproduce

1. create payment intent with 3d secure card enabled
2. try to call cancel payment intent method
3. it returns glitch

### Expected behavior

It should cancel the actual payment intent.

### OS

windows

### PHP version

7.4.20

### Library version

v3.13.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@brijesh-bacancy The 500 is likely in your PHP code itself and not really due to the library's own code. This looks more like an integration question and I would recommend contacting our support team [here](https://support.stripe.com/contact) and sharing your exact code and they can help you debug this carefully.
