### ISSUE TITLE
curl_exec() in CurlClient.php

### ISSUE THREAD

**Issue by Nici72** [stripe/stripe-php#1511]
### Describe the bug

Warning: curl_exec() has been disabled for security reasons in ...vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 500
Hi, I can't solve this problem.
I am using CentOS 7
php 7.2
curl 7.29.0
thanks !

### To Reproduce

I've tried all sorts of options and examples

### Expected behavior

no result

### OS

CentOS 7

### PHP version

7.2

### Library version

10.14.0

### API version

2023-05-25

**Comment by remi-stripe** [comment]
Hey @Nici72 ! Our stripe-php library requires that your system supports curl for it to work. The error message you are hitting indicates that something on your server is explicitly disabling `curl_exec()`. You need to look into your relevant `php.ini` and its `disable_functions` [setting](https://www.php.net/manual/en/ini.core.php#ini.disable-functions) to ensure curl/curl_exec are allowed. If you don't know how to do this you likely will need to talk directly to your host provider (the company that hosts your code/server) so that they can help you figure this out.

I'm going to close this issue as this isn't a bug or feature request with the stripe-php library and is something you need to debug on your end instead.

**Comment by Nici72** [comment]
curl_exec() is not in the disable_functions
Thanks

**Comment by remi-stripe** [comment]
I'm sorry but you need to discuss this with your host provider or the person maintaining your server. I unfortunately can't debug why PHP is not configured properly on your machine/server. Please work directly with the support team of the company that maintains your server so that they can help you further.
