### ISSUE TITLE
unable to determine value for parameter: source (Create Card)

### ISSUE THREAD

**Issue by jabcreations** [stripe/stripe-php#1543]
### Describe the bug

The PHP / cURL documentation does not provide a literal text string example of what is used by cURL at:
https://stripe.com/docs/api/cards/create?lang=curl

The HTTP POST array bit is already confusing enough as it is.

When creating a customer the POST data is simply formatted in string=key&string=key&string=key formatting:

$post_fields = 'name='.urlencode('Cool Guy').'&email='.urlencode('cool@guy.com').'&phone=1234567890';

...which is then used at:

curl_setopt($curl_handle, CURLOPT_POSTFIELDS, $post_fields);

Simple, direct, no dozens/hundreds of lines of code.

For the text server here is just one example of the literal POST data string I've attempted:

$post_fields = 'source=[source[object]]=card&[source[number]]=4444&[source[exp_month]]=12&[source[exp_year]]=2028';

I've had many different error messages from it not seeing a source parameter (and being completely confused) to not comprehending why a number parameter is set to required fields not being set at all.

Could someone please simply provide a literal text string example of how the syntax formatting is supposed to look with an example? Also updating the documentation would be exceptionally helpful. Everything else has been fairly reasonably well documented.

### To Reproduce

$post_fields = 'source=[source[object]]=card&[source[number]]=4444&[source[exp_month]]=12&[source[exp_year]]=2028';

### Expected behavior

Documentation containing a literal string example to make the syntax formatting clear.

### OS

Windows 10 x64

### PHP version

8.2

### Library version

9001

### API version

2022-08

### Additional context

I've been through the documentation and am aware of the contrast between source (e.g. for reoccurring billing) and token (one-time only use).

However back on the client's browser the resulting source id and hash aren't referenced by this documentation. It's literally like saying, "You're supplies for the 20K mile area all prepared!" without having any idea of the destination. Furthermore there are two parts of the result object that the Stripe server returns: result.client_secret or result.id. I fully expect that I should be required to send one of those in this create card POST request yet I don't see it in the documentation.

**Comment by remi-stripe** [comment]
@jabcreations Github issues are limited to bug reports or feature requests with the stripe-php library itself. Your question is more integration support and better directed to our support team instead. You can contact them at https://support.stripe.com/contact. You can also chat with engineers on our Discord server at https://stripe.com/go/developer-chat otherwise.

To give you some quick advice though, sending raw card details server-side like you are trying to do is blocked by default on Stripe accounts and requires official approval (through our support team). The reason is that this comes with higher requirements for PCI compliance and is actively documented [here](https://stripe.com/docs/security/guide#validating-pci-compliance). Additionally, the Cards API is considered legacy and here more for backwards compatibility for older integrations. Newer integrations should be using the newer PaymentMethod [API](https://stripe.com/docs/api/payment_methods/object) associated with or PaymentIntents [API](https://stripe.com/docs/api/payment_intents) for collecting payments. There's a lot more to thisthan just passing a raw card number and expiration date to accepting payments and I would highly recommend going through our canonical integration guide first: https://stripe.com/docs/payments/accept-a-payment

Similarly the format you're using is more akin to query parameters and is usually something a developer would use when they write their own raw HTTP requests. If you are using our official PHP library, you should be using the methods directly in that library which are outlined in the API Reference too for each. But again, sending raw card details is blocked by default and unlikely to be what you really need to do.
