### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by RazorCommerce** [stripe/stripe-php#161]
We've bundled Stripe API (v2.1.1) into our eCommerce system and we have someone reporting a "class not found" error and mentioned it originates from file stripe-php-2.1.1/­tests/­DiscountTest.php and seems to be triggered by DiscountTest extends TestCase. TestCase is not found. 

Noticed none of the Stripe classes including this one have a use statement when they extend other classes. Like in this case I though we might see:

namespace Stripe;
use TestCase;
class DiscountTest extends TestCase

We don't normally see this problem, it's just been reported on 1 machine which is a VPS at Digital Ocean, CentOS 6.5 x64 with Cpanel and PHP 5.4.39.

For this same user, we found anytime there is a missing use statement the machine triggers a fatal error. Not sure if this is some kind of autoloading problem.

**Comment by bkrausz** [comment]
Thanks for the report! Can you explain the context under which this is attempting to be loaded? It looks like you've manually [copied in our library](https://github.com/RazorCommerce/razor-commerce/tree/master/razor/src/Payment/Method/Stripe/api/stripe-php-2.1.1) - what loads our code? The library is meant to be either autoloaded via composer, or manually loaded by our provided `init.php`. It doesn't look like you are doing either?

Nothing in our tests should be auto-loaded, so getting DiscountTest to be included in any live code should be impossible in a normal environment.

Also, I imagine the lack of `use TestCase;` is not the issue here. Based on the error @pvernaglia reported, PHP is correctly identifying that `Stripe\TestCase` is the class to load. It's just failing to auto-load `TestCase.php`, which, again, is not surprising since nothing in `tests` should be autoloadable.

**Comment by RazorCommerce** [comment]
Thanks for your reply. The init.php is required in https://github.com/RazorCommerce/razor-commerce/blob/master/razor/src/Payment/Method/Stripe/Stripe.php on line 76 and 87. 

The error reported happens at install (of Razor Commerce) and neither of those methods that call init.php run at that point. So what puzzles us is why in this situation there is any attempt to load anything from Stripe. Again this doesn't happen on most servers, just this particular one... but it's still important to us to find out why. And in particular why the Stripe API and this file, rather than some other file.

**Comment by bkrausz** [comment]
`init.php` does not load any of our test files, so DiscountTest is not being included there. The only way this could be happening is if someone is either manually loading it, or using an autoloader that scans for directory names. I suspect it's the latter.

If you're just copying in the Stripe library (which, again, is not recommended), you can just delete the `test` folder, since it's not needed for anything in a live environment. Beyond that, there are enough non-Stripe variables at play here that I don't think there's anything we can (or necessarily should) change that would resolve this particular issue.
