### ISSUE TITLE
Received unknown parameter: client_id when creating account link

### ISSUE THREAD

**Issue by DevShaded** [stripe/stripe-php#1641]
### Describe the bug

I was testing Stripe connect OAuth flow. In the documentation on [Test the OAuth flow](https://stripe.com/docs/connect/testing#using-oauth) When I try to create the accountLink with this library I get this error back `Received unknown parameter: client_id` 

### To Reproduce

Create an account link

### Expected behavior

I belive the account link should return a testing OAuth link.

### Code snippets

```PHP
$stripe->accountLinks->create([
  "client_id" => "ca_PSmgoIiep8bNgEY6JZJlPXgQW2aI6Gtn", // Unknown parameter
  "account" => "acct_1O...",
  "refresh_url" => "https://example.com/reauth",
  "return_url" => "https://example.com/return",
  "type" => "account_onboarding"
]);
```

### OS

macOs

### PHP version

PHP 8.3.0

### Library version

stripe/stripe-php v13.10.0

### API version

2023-10-16

**Comment by remi-stripe** [comment]
Hey @DevShaded Github issues are limited to bugs or feature requests with the stripe-php SDK itself. Your ask is more an integration support question better handled by our support team: https://support.stripe.com/contact

To unblock you though, the problem is that you're mixing up our APIs. The Create AccountLink [API](https://stripe.com/docs/api/account_links/create) is used to link an existing connected account to onboard via our Connect Onboarding product that we offer. On the other hand the OAuth flow (which we consider legacy) is used when you want a user with an existing Stripe account to connect to your own platform. This requires a custom URL that you can generate via our `OAuth` package and you can see a basic example app [here](https://github.com/stripe/stripe-php/blob/master/examples/oauth.php) for example.
