### ISSUE TITLE
Fatal Error in payment method detach action

### ISSUE THREAD

**Issue by abhigt** [stripe/stripe-php#1649]
### Describe the bug

When calling the `$stripe->paymentMethods->detach()` action, it returns fatal error when the paymentmethod_id is incorrect.

### To Reproduce

Run following code to reproduce
```
$pm_id = 'pm_1MqLiJLkdIwHu7xxxxxxxxxxxF';
try {
        $stripe = new \Stripe\StripeClient($this->secret);
        $cards = $stripe->paymentMethods->detach(
            $pm_id,
            [],
        );

    } catch (\Stripe\Error\Base $e) {
        return  ['error' => $e->getMessage()]
    );
}
```

### Expected behavior

It should return with a proper error message. 

### OS

Windows/xampp

### PHP version

PHP 8.1

### Library version

stripe-php v13.9.0

### API version

2024-01-12

**Comment by remi-stripe** [comment]
@remi-stripe This question is an integration support question and better directed to our support team instead: https://support.stripe.com/contact

To unblock you, the API will return an error if you pass an invalid PaymentMethod id `pm_123`. It will have the HTTP status set to 400 and the error `type` to `invalid_request_error`. So you need to catch `\Stripe\Exception\InvalidRequestException` instead. Otherwise you can catch the generic exception class for our API errors which would be `\Stripe\Exception\ApiErrorException`.

See the example code on [our public docs](https://docs.stripe.com/error-handling) or the example below
```
try {
  $pm = $stripe->paymentMethods->detach('pm_123');
  error_log("No error.");
} catch(\Stripe\Exception\CardException $e) {
  error_log("A payment error occurred: {$e->getError()->message}");
} catch (\Stripe\Exception\InvalidRequestException $e) {
  error_log("An invalid request occurred.");
} catch (\Stripe\Exception\ApiErrorException $e) {
  error_log("Another Stripe related exception occurred.");
}catch (Exception $e) {
  error_log("Another problem occurred, maybe unrelated to Stripe.");
}
```
