### ISSUE TITLE
Validation of payload in Webhook::constructEvent is too sensitive

### ISSUE THREAD

**Issue by linusxiong** [stripe/stripe-php#1715]
### Is your feature request related to a problem? Please describe.

In a particular environment, such as my current use of [workerman](https://github.com/walkor/workerman) + laravel10, workerman is unable to read post requests using php://input, which also means that I can't use file_get_contents('php //input') and other php://input related stuff. So in this case I can only use the request()->getContent() method in laravel10, but since I can't read php://input, laravel10 will return json_encode($_POST) as the return value, and since constructEvent requires the full use of the raw payload, even a formatting issue will cause signature verification to fail, the only thing I can use is $GLOBALS['HTTP_RAW_POST_DATA'], and this method has been deprecated by php and removed completely in the future.

getContent function in laravel 10
<img width="880" alt="image" src="https://github.com/stripe/stripe-php/assets/29816947/215569bf-a5d2-4b2d-9d3e-28a03a299d1c">

### Describe the solution you'd like

Let signature verification ignore its formatting, such as indentation and line breaks, etc.

### Additional context

Thank you very much for considering my request, and please let me know if there are any other ways available to me!

**Comment by helenye-stripe** [comment]
Hi! Unfortunately, we don't intend to change the behavior of webhook signature verification. Any modifications (especially more load-bearing ones as json_encode) will make it difficult for us to compute the signature to compare against, since we cannot guarantee the types of changes that have been made. I would recommend consulting laravel to add a toggle to disable this JSON encoding before retrieving the body, as being able to access the raw POST body is not an uncommon request.
