### ISSUE TITLE
Must provide source or customer - On Live Environment 

### ISSUE THREAD

**Issue by hajindersingh645** [stripe/stripe-php#180]
I'm facing a weird kind of error. It all works good on test environment, but as soon as switch back to live environment it give the error.

Can someone help me on this.

Following is the log :

Response body

{
error:
    { 
      type: "invalid_request_error"
      message: "Must provide source or customer."
    }
}

**Comment by matthewarkin** [comment]
What's the code that triggers this error?

**Comment by hajindersingh645** [comment]
@matthewarkin I have been using the following code

```
$charge = \Stripe\Charge::create(array(
	  'amount' => $actualFee,
	  'currency' => 'usd',
	  'source' => $_POST['stripeToken'],
	  'application_fee' => $applicationFeeinCents
	), array('stripe_account' => $userAccount['stripe_acc_id']));
```

We are deducting fees on every transaction, after getting **$userAccount['stripe_acc_id']** which is stripe account id saved in our database as you would have noticed.


Thanks

**Comment by matthewarkin** [comment]
I'm going to assume that you're not checking if `$_POST['stripeToken']` is set to `NULL`?

**Comment by hajindersingh645** [comment]
@matthewarkin I surely check for that. But even if that is the case why it is working on test environment. Can you enlighten on that please?

**Comment by bkrausz** [comment]
@hajindersingh645 it seems likely that in some cases `$_POST['stripeToken']` is being set to an empty string or null. I'd recommend going into your "logs" tab and seeing what parameters are actually making it to Stripe's servers.

Any further debugging would require actually digging into specific information about your account. You should email support@stripe.com for that. Given that it's incredibly unlikely that this is due to a bug in the Stripe PHP library, I'm closing this issue out. If there is a bug on our end that we need to fix, support@stripe.com will be able to route it appropriately.
