### ISSUE TITLE
How to use stripe-php behind a proxy ?

### ISSUE THREAD

**Issue by na-ji** [stripe/stripe-php#207]
Hello !

I'm now deploying a website using Stripe and I encountered a problem. All the outgoing request from my server must pass by a proxy. Is there a way to configure stripe-php to use the proxy ? 
Like in cURL where we can use the options CURLOPT_PROXY and CURLOPT_HTTPPROXYTUNNEL to configure the proxy.

Thanks for your answer !

**Comment by remistr** [comment]
Hey @na-ji!

The best solution for you would be to modify the code for `request()` to handle the proxy setup on your end as I don't think we support anything like this at the moment. We rely on cURL on our end too so you'd configure it to support your proxy directly in  [CurlClient.php](https://github.com/stripe/stripe-php/blob/983887d49d9caa96079a57858ace88e6ae3b89bf/lib/HttpClient/CurlClient.php#L21)

**Comment by na-ji** [comment]
Ok it's what I did but I don't like modifying vendors because it will be discarded on update. It's should be an option to use, like stripe-java where we can easily configure the proxy. 

Maybe I can implement this and do a PR ?

**Comment by remistr** [comment]
@na-ji You can definitely modify this and submit a PR with some tests and we'll see if we can merge it!

**Comment by bkrausz** [comment]
You also should be able to write your own replacement for CurlClient, and plug that into our system without needing the change any stripe-php code.

**Comment by iansltx** [comment]
While implementing your own CurlClient is all well and good, that throws out all of the painstaking conventions the existing client has (e.g. around timeouts ;) ) so probably shouldn't be required to add a proxy (one more curl_setopt() call).

On top of that, looked at the CurlClient again and there's no easy way to extend it while tweaking a minor aspect of the client's behavior...the handle gets init'd and exec'd in the same call without any hooks (flag/value checks like timeouts and SSL verification don't count IMO).

Since I need proxy support for a project that just switched to Stripe, I'll build a tweaked CurlClient allowing that and PR, plus maybe a PoC for injecting a callable that can return an array of curlopts at L57 of CurlClient.php. Anything that needs to stay as-is will get overwritten later in the process, though maybe that's a bit _too_ much flexibility and should stay out of the mainline library :)

**Comment by brandur** [comment]
@iansltx Good points! I'll definitely be happy to take a look at that PR.

**Comment by iansltx** [comment]
#234 has an impl that allows either a callable or a static array to be supplied with base options. Was going to add some more methods and then realized that there are multiple knobs to turn on proxy in addition to the one I need (only CURLOPT_PROXY), and if you need that functionality you probably know which CURLOPT_* flags to flip anyway because you've done it elsewhere in your code base.

Looks like tests are green except for what's failing from earlier (live transfers, five tests). Maybe the test suite should allow those exceptions as a valid outcome so all the builds aren't failing? :)

**Comment by iansltx** [comment]
@remistr @na-ji Now that the above is merged, you can add proxy options without replacing CurlClient or revising vendored code :)
