### ISSUE TITLE
Coupon Code usage example

### ISSUE THREAD

**Issue by TrangDinhVan** [stripe/stripe-php#225]
Could you please give me an example of how to use Stripe Coupon code with this stripe-php source code.

**Comment by remistr** [comment]
Hey @TrangDinhVan 

We have lots of documentation on our website directly:
- https://stripe.com/docs/api#create_coupon
- https://stripe.com/docs/api#create_subscription
- https://stripe.com/docs/guides/subscriptions#applying-discounts

Otherwise, I'd recommend reaching out to support for direct help here https://support.stripe.com/email

Issues should be limited to bugs on our PHP library!
