### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by yespbs** [stripe/stripe-php#238]
Avast on Mac shows warning with latest version v3.11.0 when updated by composer

lib/ApplicationFeeRefund.php
lib/Subscription.php
lib/TransferReversal.php
tests/RequestOptionsTest.php

Could you check if any infection occurred withing github,
![screen shot 2016-03-29 at 9 50 47 am](https://cloud.githubusercontent.com/assets/478293/14097857/910b0eee-f593-11e5-8126-163d89af7704.png)

**Comment by curtisblackwell** [comment]
Probably a false positive. See #237.

**Comment by yespbs** [comment]
I check each file and found no issue, but unfotunately avast is deleting these file and some of which are important. I am not sure why this is becoming false positive ONLY when other files are passed without issue!!!. 

I believe the api library is ok but its spammed by github. Could have the repo scanned by github and some antivirus if possible? 

This is only one github package that fails with Avast and I think there something wrong

**Comment by GrahamCampbell** [comment]
Yeh, this is clearly a false positive.

**Comment by brandur** [comment]
@curtisblackwell @GrahamCampbell Thanks for the assist guys!

@yespbs I'm closing this out because we're not distributing malware with stripe-php, and this is most likely a false positive. On your end, there may be a few things to look into:

* If you're fetching the package using an insecure mirror (i.e. no TLS and no checksums, or checksums that didn't come in over TLS), there is a possibility that a MITM modified it en route. It may be worth looking into the exact files that you have on disk there that are being flagged to see if there's anything that looks suspicious. If you see anything, let me know immediately and please describe your packaging setup.
* Does Avast give you any details as to what exactly it found in the files? (Besides "Other:Malware-gen" of course.)

I've also opened a ticket with Avast just to see if that goes anywhere.

**Comment by yespbs** [comment]
I have checked exact files and seems all clean, if you have submitted to avast that ok, I will try to submit to Avast too from virus chest

**Comment by brandur** [comment]
I heard back from Avast and they recommended that I follow their process for submitting a whitelist request. On the page describing that process, they acknowledge that they have a very high rate of false positives (hence the well-documented process around the whitelist), so I'm not too concerned here that there is actually any security risk here.

I want to avoid getting into a not-particularly-constructive habit of submitting whitelist requests to Avast every time they improperly flag one of our files as malicious, so I'm _not_ going to submit a whitelist request. Let me know if anyone disagrees with this of course, and we can discuss further.

@yespbs I'd recommend doing whatever you can do here to manually whitelist the files from the software you're using, but given that this is an Avast bug, I'd suggest trying to find a longer term solution with them.

**Comment by yespbs** [comment]
@brandur could you paste the url and process, I can do it since it for my benefit

**Comment by brandur** [comment]
@yespbs Sure! The process for whitelisting is here:

https://www.avast.com/faq.php?article=AVKB229#artTitle
