### ISSUE TITLE
Integrating Stripe module in drupal issues

### ISSUE THREAD

**Issue by babitabhandari** [stripe/stripe-php#245]
When i tried to integrate webform stripe module in drupal.It told me to install php library in it.When i used my webform and tried to click on submit button it goes to payment mode.after filling the information of card number and all that When i click submit button then it shows error in line  as follows:- 

`\Stripe\Stripe::setApiKey(variable_get('webform_stripe_secret_key', 'sk_test_XXX')); `

> Fatal error: Class 'Stripe\Stripe' not found in
> C:\wamp\www\drupal\sites\all\modules\webform_stripe\webform_stripe.webform.inc on line 129.
So please can you resolve this error.

**Comment by remistr** [comment]
@babitabhandari The issue here is that you didn't properly include the PHP library in your project. You'd need to either use Composer as explained [here](https://github.com/stripe/stripe-php#composer) or the manual installation as explained [here](https://github.com/stripe/stripe-php#manual-installation)

Separately, make sure to never share your Secret API key, even the test one. And for those types of questions, writing to support is usually the best flow as issues on Github should really be limited to bugs on the library and not questions on how to use it! You can contact support [here](https://support.stripe.com/email)

**Comment by babitabhandari** [comment]
Sir Please tell me how to include file in my project because when i use require_once(); it halt the execution and cause fatal error

**Comment by matthewarkin** [comment]
Have you read the manual installation instructions from https://github.com/stripe/stripe-php#manual-installation? You'll have to replace the path with the correct path and it sounds like you're using the wrong one.

**Comment by babitabhandari** [comment]
Yes Sir, I have read the manual instructions and download the latest version of php libraries. Please can you tell me how to include file path.I have installed the php library in library folder and my webform stripe folder is located in modules folder.both are separated.Now the problem is i want to fetch php library in  module folder.For this i have used require_once(./stripe-php/init.php'); but it causes fatal errors.My php libraries file is located in C://wamp/www/drupal/sites/all/libraries/stripe-php/init.php.Now you just tell me how to include this file.

**Comment by curtisblackwell** [comment]
This sounds like it may be better to ask someone who builds Drupal modules. Your problem isn't with Stripe, but with directory structure.

**Comment by babitabhandari** [comment]
I have solve this issue.Actually the main problem was about require_once line.now its working and had successfully working payment in testing mode.
