### ISSUE TITLE
Version jump?

### ISSUE THREAD

**Issue by dopesong** [stripe/stripe-php#249]
I'm interested why you jumped from v3.12.1 to v3.22.0?

**Comment by kyleconroy** [comment]
@dopesong Whoops, that was my mistake. I meant to update to `v3.13.0`. I've corrected the mistake.

**Comment by aaronhuisinga** [comment]
Hey @kyleconroy, I just wanted to point out that there might be more of an issue here than it seemed before. I've been using the Stripe PHP package in our production web app for a few years, and ran a `composer update` while the mistaken version 3.22.0 was available. Composer updated us to what it thought was the latest version (3.22.0). Problem being, every time we checked for an update, Composer saw that the version we had installed (v3.22.0) was greater than the latest available version (currently v3.20.0). 

The only reason that I even caught this was that I received an email from Stripe warning us that TLS 1.0 and 1.1 were being deprecated and that we were using a version of the Stripe PHP package that would cease to work On January 1, 2017 or May 1, 2017.

I was forced to clear our Composer cache, manually update the composer.json file to install v3.20.0, and then switch back to the proper versioning in the composer.json file. We're now back up and running with the proper latest release, but I'm assuming since this happened to us, there are probably several other instances of this same issue that developers haven't yet discovered.

Normally this issue would take care of itself by the time v3.23.0 releases, but if Stripe is dropping support for TLS 1.0 and 1.1, some developer teams might find themselves surprised by why their app isn't working anymore. Not sure of the best way to let developers know about this, but I figured I should let you and the Stripe team know about the possible issue.

**Comment by brandur** [comment]
Hi @aaronhuisinga, thanks a lot for writing in and letting us know about this one!

I just looked and luckily it looks like we only have 5 merchants that are using the mistaken version, and I should be able to let them know pretty easily. Would you mind emailing me your merchant ID (i.e. usually looks like `acct_xxx`) so I can take you off the list? I'm at brandur@stripe.com.

**Comment by aaronhuisinga** [comment]
Thanks @brandur! I emailed you.

**Comment by dopesong** [comment]
Great support stripe guys! Thumbs up! 👍 💯

**Comment by brandur** [comment]
All users on that version have been notified!
