### ISSUE TITLE
I used version 1.8.0 stripe-php

### ISSUE THREAD

**Issue by mahesfsp** [stripe/stripe-php#253]
In this stripe component 
  public function cancelSubscription($params=null)
  {
    $requestor = new Stripe_ApiRequestor($this->_apiKey);
    $url = $this->instanceUrl() . '/subscription';
    list($response, $apiKey) = $requestor->request('delete', $url, $params);
    $this->refreshFrom(array('subscription' => $response), $apiKey, true);
    return $this->subscription;
  }

cancel and update subscription are not worked for me.

**Comment by remistr** [comment]
@mahesfsp: This is a _really_ old version of our library that was released more than three years ago: https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#180-2013-04-11

As far as I'm aware it should just work as expected assuming that you're on an API version old enough to support the old situation where only one subscription was supported per customer.

I'd recommend that you contact Stripe support directly to discuss the exact error you're experiencing so that they can help: https://support.stripe.com/email
