### ISSUE TITLE
Stripe/stripe-php v3.13.0 version i used

### ISSUE THREAD

**Issue by mahesfsp** [stripe/stripe-php#254]
Could you please tell me , current v3.13.0 is support update and cancel subscription ? customer able to update the more than one subscription ?

**Comment by remistr** [comment]
@mahesfsp : Yes it does.

I wanted to restate what I said in the previous issue you opened. Issues on Github are here to report bugs on the libraries or feature requests. Since you mainly have questions about the integration and how the library works, it'd be way better if you contacted support directly instead! You can do this here: https://support.stripe.com/email
