### ISSUE TITLE
where to put this?

### ISSUE THREAD

**Issue by bradseth** [stripe/stripe-php#292]
where should I put this?

require_once('vendor/autoload.php');

**Comment by remistr** [comment]
@bradseth: Github issues should be limited to bug reports around our PHP library. Since your question is not a bug report, you should talk to Stripe support instead here: https://support.stripe.com/email

Since I'm here though I can answer quickly, but any follow up should go through support, hope that's okay!

That line of code should be added to your project where you plan to use Stripe. So let's say you have a `ChargeController` class or a `charges.php` script, you'd want to make sure this script includes our library since you plan to use it.

This is specific to Composer. If you don't use Composer you should download the library directly and install it manually as explained here: https://github.com/stripe/stripe-php#manual-installation
