### ISSUE TITLE
Re-create plan.

### ISSUE THREAD

**Issue by AndriySvirin** [stripe/stripe-php#295]
Hey there,

What I do wrong?
I wish to update plan price, and will delete old and create same new plan with new price.
After I re-create i can't retrieve subscriptions by "plan".
Is it right?

**Comment by remistr** [comment]
@AndriySvirin: The issues here should be limited to bug reports with the PHP library and not for technical help. In the future you should contact support directly [here](https://support.stripe.com/email).

Since I'm here though, let me answer: this is expected behaviour. When you delete a plan and create a new one, even if it has the same id it's still a different plan so you have no way to retrieve customers with a subscription on the old plan itself. I would recommend getting the full list before doing that operation or always using a different plan id otherwise.
