### ISSUE TITLE
TLS version

### ISSUE THREAD

**Issue by elarion83** [stripe/stripe-php#301]
Hi ! I have an issue with my TLS version.

Stripe tell me that I should upgrade to 1.2 but I don't know how and there is no clear tutorial.

Please can you help me ?

**Comment by dextermb** [comment]
@elarion83 Check the README, it'll direct you to a link on the stripe website to run a test ([Link for the lazy](https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#php)).

What output do you get?

**Comment by elarion83** [comment]
I've already test my TLS and the output is that tls 1.2 is not supported.

So I read the instructions below but my host is OVH (French) and upgraded my php version to php7 but there is no change.

**Comment by dextermb** [comment]
@brandur TLS 1.2 isn't forced anymore since [v4.0.0](https://github.com/stripe/stripe-php/releases/tag/v4.0.0), stripe should continue to work even if the user isn't running TLS 1.2?

@elarion83 are you using the latest release? [v4.0.0](https://github.com/stripe/stripe-php/releases/tag/v4.0.0)

**Comment by elarion83** [comment]
Yeah I'm using the v4.0.0

**Comment by olivierbellone** [comment]
Hi @elarion83. Please note that GitHub issues are for bugs or feature requests with our PHP library. If you have issues or queries about how to use the library, you should instead contact Stripe's support here: https://support.stripe.com/email.

That said, in order to solve your issue, you likely need to upgrade the software packages for curl and OpenSSL as well as PHP, then restart your web server. You can find generic upgrade instructions here:
- https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2
- https://support.stripe.com/questions/how-do-i-upgrade-my-openssl-to-support-tls-1-2

**Comment by elarion83** [comment]
Yeah but right now I'm using your library and I have an issue. So that's why I'm posting right here.

The first link you sent is the same link Dextermb sent to me. And for the second I had already upgraded my development environment. 

I got no answer from Stripe. And that GitHub issue are for bugs with your PHP library, which is the point here.

**Comment by elarion83** [comment]
Why do you close this issue ? It's not resolved and the issue is from your library, dafuq ?

**Comment by olivierbellone** [comment]
@elarion83 I closed the issue because it's not a bug with the library. If your server can't use TLS 1.2 for outbound connections, there's nothing the library can do about it. You need to upgrade your server's curl and OpenSSL software packages as stated above.

I wasn't able to find your request to Stripe's support. Can you tell me what the email address for your Stripe account is?

**Comment by olivierbellone** [comment]
@dextermb See #299 for more context on why the library is no longer forcing the `CURLOPT_SSLVERSION` configuration option. In a nutshell, not setting the option will result in the highest available TLS version being used in _most_ cases. Some systems (older CentOS / RHEL versions) might need to use the `CURLOPT_SSLVERSION` to explicitly opt in to TLS 1.2, which they can now do manually after loading the library.
