### ISSUE TITLE
exception 'Stripe_InvalidRequestError' with message 'No such token: tok_19BOBLBHN5lCF43SAI4iHnoB'

### ISSUE THREAD

**Issue by bswscube** [stripe/stripe-php#308]
exception 'Stripe_InvalidRequestError' with message 'No such token: tok_19BOBLBHN5lCF43SAI4iHnoB' in /home/apporio/public_html/demo.apporio.com/integrate-stripe-payment-gateway/Stripe/lib/Stripe/ApiRequestor.php:147 

I am using testing mode API. Please help as soon as possible.

**Comment by ob-stripe** [comment]
Hi @bswscube, this is also a problem with your Stripe integration and not a bug with the PHP library. You need to reach out to support directly at https://support.stripe.com/email, as issues in this GitHub repository are only for bugs or feature requests with Stripe's PHP library. Thanks for your understanding.

**Comment by sanjaykumar2338** [comment]
@ob-stripe 

Facing a same issue:- No such token: tok_1DZuJQ4Ylaxqboil77drAIzj

Here is my request 

$customer = \Stripe\Customer::create(array(
				'email' => $this->input->post('stripeEmail', TRUE),
				'source'  => $this->input->post('stripeToken', TRUE),
				'plan' => 'yearly-unlimited'
			));

**Comment by remi-stripe** [comment]
Hello @sanjaykumar2338. This would be the same answer as the message above. This is an issue with your integration and not the code or the library and the best solution here is to double check your API keys. You are likely creating a token with the Publishable key from one account and then trying to use it with the Secret key of another account. Otherwise, please reach out to our support team here: https://support.stripe.com/email
