### ISSUE TITLE
Master build is failing

### ISSUE THREAD

**Issue by brandur** [stripe/stripe-php#315]
Unfortunately some bad subscription tests were added.

https://travis-ci.org/stripe/stripe-php/jobs/181375624

**Comment by dpetrovics-stripe** [comment]
Looks like the two failing tests are here: https://github.com/stripe/stripe-php/blob/master/tests/SubscriptionTest.php, but they don't seem to have been changed since September https://github.com/stripe/stripe-php/commits/master/tests/SubscriptionTest.php.

Based on the error in the test, I think this may be due to a server side change to enforce plan uniqueness which occurred around the same time as the failures. (And the error codes match). cc @kjc-stripe

**Comment by brandur** [comment]
@dpetrovics-stripe Yeah, that hypothesis sounds about right to me. Added a fix in #317 to see if we can get this patched up.
