### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Cavain** [stripe/stripe-php#336]
Hello,

Module was not working correctly i think . I have been facing 500 HTTP Error after following  all the instructions in the last when i was testing the module i got that error on domain.com/whmcs/ccpay.php . What was the problem is? and how to fix it?

Regards

**Comment by remi-stripe** [comment]
@Cavain HTTP 500 usually happens when there is something wrong in your code and you're not handling errors/exceptions properly. Based on the path to the file, you seem to be using a third-party plugin for WHMCS. You will need to reach out to the developers of that plugin directly as it wasn't built by Stripe and the error wouldn't be in our library.
