### ISSUE TITLE
Why static functions instead of OOP?

### ISSUE THREAD

**Issue by JulesAU** [stripe/stripe-php#36]
It's effectively impossible to write testable code utilising this abstraction layer, without all of your tests making real calls to the Stripe API.

Any OOP Stripe libraries available for PHP?

**Comment by josecelano** [comment]
@bkrausz could you paste here a concrete example?

**Comment by bkrausz** [comment]
@josecelano A concrete example of what?

**Comment by josecelano** [comment]
@bkrausz 

>"ex: if your init method is the only thing that has access to a config, but has no ability to pass objects around"

I mean one scenario where you can use static methid but not instantiate a new object.

I´m building a PHP client for a REST API and I have seen other clients (not only this one) using static methods.

**Comment by bkrausz** [comment]
I see. Instantiating an object is better programming practice, though it's more obvious to just use static methods. It's always *possible* to instantiate an object and restructure things so it's passed around, but it requires a bit more thought as to how the code is setup.

For example, a basic (not ideal, but commonplace) PHP setup may look like this:

config.php:
```
<?php
\Stripe::Stripe::setApiKey('...');
// ...
```

charge_page.php
```
<?php
require_once('./config.php');
if ($_SERVER['HTTP_METHOD'] == 'POST') {
  // ...
  \Stripe::Charge::create(/*...*/);
}
```

This is *NOT* a good way to structure an application, but is the most obvious first step when making a website. If you had to instantiate an object, you would instead end up doing something like:

config.php:
```
<?php
function getStripe() {
  new \Stripe::Stripe('...');
}
// ...
```

charge_page.php
```
<?php
require_once('./config.php');
if ($_SERVER['HTTP_METHOD'] == 'POST') {
  // ...
  getStripe()->chargeCreate(/*...*/);
}
```

Note that this is also not ideal, and instead you should be using a framework like [larvel](http://laravel.com/) that provides routing.

Unless your website has tests or is large enough for some infrastructural reuse, the 2nd method (instantiation) just looks like a lot of extra work. That's why static methods tend to be popular: they're conceptually very accessible to new developers, though they are more painful for large web application who invest properly in testing and have more code reuse.

**Comment by mattsnowboard** [comment]
I'm not sure that promoting poor practices (as you said, "This is NOT a good way to structure an application") is a good reason to keep the library the way it is. In fact, in your second example, you could just instantiate the object immediately before use and it's a 1-line addition for people who aren't doing things properly. Also, if you say "Unless your website has tests" and imply that most sites don't, that's also a bad practice to be promoting. Especially when we're talking about the part of a site that is processing payments.

I feel that the best idea is to increment the version number for a refactored library that promotes good practices (making applications more easily unit testable, etc.). Let people who don't care about their application stick with 2.x and build a better version in a 3.x branch.

On the other hand, I understand that it would take a lot of work and so it may not be possible to get this done in a reasonable amount of time.

**Comment by JulesAU** [comment]
Big +1 for Matt's comment. Unit (and indeed integration) tests are absolutely critical for payment processing code. 

Needless to say that we rolled our own integration shortly after opening this issue 2 years ago (although sorry to say not fit for public consumption).

**Comment by josecelano** [comment]
thanks @bkrausz for your reply. I was very curious to know about the reasons as it seems to be a very common practice. Static methods are also used by [PayPal PHP SDK](https://github.com/paypal/PayPal-PHP-SDK). I also use them becuase it seems to be easier to use but I think I have changed my mind becuase:

1.- Testing: It seems that supoprt for static methods have been deprecated in PHPUnit.
https://github.com/sebastianbergmann/phpunit-documentation/issues/77

2.- Ease of use: really I do not think there is much more complexity in your second example. An the user could add a static wrapper.

3.- In some scenarios it is the only slocution available. 
This is why I askek you about the concrete sample. The only scenario I had found if this one:

```php
<?php
$result = array_reduce([1,2,3], 'Charge::create', 0);
```

extracted from a @mathiasverraes `s blog post:
http://verraes.net/2014/06/when-to-use-static-methods-in-php/
but I suppose you can create a class with a static method and use the intantiated object inside that method. Probably the performace would be worse but I agree that tests should be critical for a payment processing code.

**Comment by GrahamCampbell** [comment]
> I was very curious to know about the reasons as it seems to be a very common practice.

The biggest reason I see in SDKs is because they're just ports from other languages...

**Comment by bkrausz** [comment]
@mattsnowboard I entirely agree, and would love to get us onto object instantiation. With a tiny bit of magic it wouldn't be hard to support both as well. Regardless of that, it's just something I haven't had time to get to in the big list-o-priorities. Was mostly providing some historical context on why someone would have chosen that (as we did 5 years ago when this library was first written, and the PHP world looked quite different).
