### ISSUE TITLE
Can't create an order

### ISSUE THREAD

**Issue by icemanblas** [stripe/stripe-php#381]
Hello, 

I'm trying to create an Order via the Stripe checkout form, but with no success. I'm calling the create method on the "Order" class, all the products and SKUs are correct and in stock, and the customer is created/retrieved and passed as parameter. Here's the sample code, I'm using the Stripe TEST mode (package version 5.2.0):

It's like the code is not executed at all:

```php
Stripe::setApiKey("SECRET");

// ....

return Order::create([
    'stripe_account' => $customer->id,
    'currency' => 'usd',
    'items' => ['type' => 'sku', 'parent' => 1, 'quantity' => 1]
]);
```
Am I missing something? Thanks in advance

**Comment by ob-stripe** [comment]
Hi @icemanblas. The `stripe_account` parameter is used by Connect platforms to issue requests on behalf of other accounts (cf. [here](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header)). If you want to charge a paying customer, you should pass the customer ID (`"cus_..."`) in the [`customer`](https://stripe.com/docs/api/php#create_order-customer) parameter instead.

As this does not seem to be a bug with the PHP library, I'm closing the issue here. You can reach out to support at https://support.stripe.com/email if you need more help with this.

**Comment by icemanblas** [comment]
@ob-stripe 
Yes, that was an honest mistake on my side. However, the issue is still there, so I will contact support. Thanks for the help.
