### ISSUE TITLE
`deleteDiscount` returns `null`

### ISSUE THREAD

**Issue by joseym** [stripe/stripe-php#40]
Working on an adapter for LithiumPHP and noticed that the deleteDiscount method always returns null upon success (verified coupon deletion in customer panel).

**Comment by sjelfull** [comment]
Isn't the docs incorrect there? It says example response:
```php
Stripe\Discount JSON: {
  "object": "discount",
  "deleted": true
}
```
I was bitten by this just now as well.

**Comment by remi-stripe** [comment]
The API does return the JSON you mentioned but the stripe-php library does not at the moment. It updates the customer's instance to remove the discount as you can see in the code [here|https://github.com/stripe/stripe-php/blob/master/lib/Customer.php#L140] but it does not return anything.

I'm not entirely sure why we made this choice but we should fix it. The issue is that this would be a breaking change and we would have to release a major version of the library for this so we won't do this immediately. I'm adding this as a future fix though.
