### ISSUE TITLE
Deprecate `Stripe\JsonSerializable` and bump minimum version to PHP 5.4 (or later)

### ISSUE THREAD

**Issue by twoixter** [stripe/stripe-php#406]
PHP version 5.3 is at End of Life cycle for at least 3 years now. The file `./lib/JsonSerializable.php` as a bridge for the `\JsonSerializable` interface prevents execution of the AspectMock library for testing, apart from not being PSR-2 compliant.

[AspectMock](https://github.com/Codeception/AspectMock) library from Codeception is a powerful mocking library we use to test static methods and mock objects but it parses PHP files on their own and doesn't recognise the special syntax used (`interface` declarations must be at root).

This issue is a suggestion to make the current version usable much like the v1.18.0 version for PHP 5.2, as specified in [Legacy Version Support](https://github.com/stripe/stripe-php/#legacy-version-support).

**Comment by ob-stripe** [comment]
Hi @twoixter, thanks for this report. We've held off dropping support for PHP 5.3 and other post-EOL versions because a non-negligible part of Stripe users are still using those versions.

That said, I agree it's time we reconsider this position, at least for 5.3. We will discuss this internally once the new year break is over, but I'm leaving the issue open so that anyone can contribute to the discussion -- data points such as the AspectMock compatibility issue you mentioned are very valuable to us and will help us make an informed decision.
