### ISSUE TITLE
Unexpected error communicating with Stripe. If this problem persists, let us know at support@stripe.com. (Network error [errno 35]: Encountered end of file)

### ISSUE THREAD

**Issue by abhinavek** [stripe/stripe-php#416]
i am having problem with stripe it is showing this error below

```
Type: Stripe\Error\ApiConnection

Message: Unexpected error communicating with Stripe. If this problem persists, let us know at support@stripe.com. (Network error [errno 35]: Encountered end of file)

Filename: /home/abhinav/public_html/quote/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php

Line Number: 251

Backtrace:

File: /home/abhinav/public_html/quote/vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php
Line: 213
Function: handleCurlError

File: /home/abhinav/public_html/quote/vendor/stripe/stripe-php/lib/ApiRequestor.php
Line: 223
Function: request

File: /home/abhinav/public_html/quote/vendor/stripe/stripe-php/lib/ApiRequestor.php
Line: 64
Function: _requestRaw

File: /home/abhinav/public_html/quote/vendor/stripe/stripe-php/lib/ApiResource.php
Line: 120
Function: request

File: /home/abhinav/public_html/quote/vendor/stripe/stripe-php/lib/ApiResource.php
Line: 142
Function: _staticRequest

File: /home/abhinav/public_html/quote/vendor/stripe/stripe-php/lib/Charge.php
Line: 62
Function: _all

File: /home/abhinav/public_html/quote/application/controllers/Stripe.php
Line: 35
Function: all
```

**Comment by remi-stripe** [comment]
@abhinavek Can you run [this script](https://gist.github.com/olivierbellone/9f93efe9bd68de33e9b3a3afbd3835cf) on your server and let us know the results?

**Comment by abhinavek** [comment]
@remi-stripe hi. i have run the script and this is what i got.

```
OS: Linux
uname: Linux e2e-11-110.e2enetworks.net.in 3.10.0-229.7.2.el7.centos.onapp.x86_64 #1 SMP Thu Jul 2 12:23:16 EEST 2015 x86_64
PHP version: 7.0.24
curl version: 7.57.0
SSL version: NSS/3.28.4
SSL version number: 0
OPENSSL_VERSION_NUMBER: 100020bf
TLS test (default): TLS 1.0
TLS test (TLS_v1): TLS 1.0
TLS test (TLS_v1_2): TLS 1.2

```

**Comment by remi-stripe** [comment]
Okay so the issue here seems to be that your installation is configured with TLS 1.0 by default. What you want to do here is upgrade your PHP installation to always use TLS 1.2 by default.

We have instructions on how to do this on our support page: https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#php

If you are still stuck, you can reach out to our support team to help you debug this as it's not an issue with the library itself: https://support.stripe.com/email

**Comment by abhinavek** [comment]
i have already done that .
and still not working.
and i have force tls version 1.2 and it is working. but is there any patch or version update to solve from your end?

**Comment by ob-stripe** [comment]
@abhinavek The issue is that the SSL library used by the curl module of your PHP environment (NSS/3.28.4) does not enable TLS 1.2 by default. I'm not sure why that's the case, as it's a recent version -- it might be something specific to your environment.

You can use the solution described [here](https://github.com/stripe/stripe-php#ssl--tls-compatibility-issues) to force the use of TLS 1.2:
```php
$curl = new \Stripe\HttpClient\CurlClient([CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_2]);
\Stripe\ApiRequestor::setHttpClient($curl);
```

This is not something that we can enable automatically in the library as it would cause issues in other environments.

Ideally, you should upgrade your environment so that the curl module uses an up-to-date SSL library that always defaults to TLS 1.2. If you are using CentOS or Red Hat, some users have reported success by running the following commands as root:
```
# rpm -Uvh https://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/l/libnghttp2-1.6.0-1.el6.1.i686.rpm
# rpm -Uvh https://mirror.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-1-13.rhel6.noarch.rpm
# yum -y install libcurl
# apachectl restart
```

This should upgrade the curl module to a version that's linked against a recent OpenSSL version (rather than NSS), which should always default to TLS 1.2. Use these commands at your own risk -- I recommend consulting with your network administrator and/or hosting provider first to see if there is a better way of ensuring your system uses TLS 1.2.

**Comment by abhinavek** [comment]
This saying error.
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:
       
         1. You have an upgrade for libnghttp2 which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of libnghttp2 of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude libnghttp2.otherarch ... this should give you an error
            message showing the root cause of the problem.
       
         2. You have multiple architectures of libnghttp2 installed, but
            yum can only see an upgrade for one of those architectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.
       
         3. You have duplicate versions of libnghttp2 installed already.
            You can use "yum check" to get yum show these errors.
       
       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).
       
       Protected multilib versions: libnghttp2-1.21.1-1.el7.x86_64 != libnghttp2-1.6.0-1.el6.1.i686

**Comment by ob-stripe** [comment]
@abhinavek It sounds like libnghttp2 is already installed in your environment so you might be able to skip the first command. Though again, I recommend consulting with your administrator or hosting provider to receive more help here -- this is more of a CentOS issue than it is a Stripe one.
