### ISSUE TITLE
__toArray

### ISSUE THREAD

**Issue by lukeholder** [stripe/stripe-php#42]
where is the documentation around the coercion methods like __toArray and __toJson ? Its unusable to return the stripe object in templates even though it tried to act like an array, with various template languages it fails.

**Comment by curtisblackwell** [comment]
I'm in a similar situation (with a different CMS), where I want to return  everything in `_values` as an array for use in template tags. `keys()` doesn't work for me, because it just calls `array_keys()`, so none of the data makes it back. I've been using `__toArray(true)`.

If I'm not supposed to use `__toArray()`, what am I supposed to use?

**Comment by bkrausz** [comment]
We *should* make Objects iterable, so that you can use `foreach` on them. In lieu of that I'd feel free to use `__toArray` for now.

**Comment by curtisblackwell** [comment]
Cool, thanks. What's the harm in making `__toArray()` a permanent solution (from your end)?

**Comment by bkrausz** [comment]
Practically just the commitment not to change the response format. I don't think we would anyway, which is why this is fine for now. I just haven't put any thought into if we should/shouldn't commit to that.

**Comment by curtisblackwell** [comment]
Ah, thanks for taking the time to answer.
