### ISSUE TITLE
detach source method not found?

### ISSUE THREAD

**Issue by bigzoo** [stripe/stripe-php#432]
I'm doing an implementation in a Laravel project and I'm having an issue with detaching a source.
My implementation is as documented [here](https://stripe.com/docs/api#detach_source). 
Code sample
```
    /**
     * Remove an existing Source
     * @param string $source_reference_id
     * @param string $stripe_customer_id
     * @return mixed
     */
    public function removeSource(string $source_reference_id, string $stripe_customer_id)
    {
        $customer = StripeCustomer::retrieve($stripe_customer_id);

        // Bug identified
        $customer->sources->retrieve($source_reference_id)->detach();
    }
```

Response I am getting is:
```
[2018-02-09 09:48:40] testing.ERROR: Call to undefined method Stripe\Card::detach() {"userId":1,"email":"josiah.langosh@example.net","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Stripe\\Card::detach() at .../app/Services/Payments/Methods/StripePaymentsServiceProvider.php:31)
```

Might the package have been updated and the docs not?

Versions: 
Laravel:      "laravel/framework": "5.5.*"
Stripe-php: "stripe/stripe-php": "^5.9"

**Comment by bigzoo** [comment]
I ended up replacing detach with delete. The retrieve method was returning an instance of a Card and not a Source.

**Comment by remi-stripe** [comment]
@bigzoo `detach()` was added in stripe-php 5.3.0 [here](https://github.com/stripe/stripe-php/blob/5e27a67ef7f1797c238efdef0a3dfdab504acf25/lib/Source.php#L40) so you should have it. It also only works on Sources and it would not work on Cards. My guess is that your code is using Card objects (and creating tokens client-side) instead of Sources which is why it was failing. In that case `delete()` is the right method to call.

**Comment by bigzoo** [comment]
Well I guess I was getting cards. I do have a question though. Why is it that when creating a Customer  over the api with a given 'tok_visa' token, the sources array within the response contains a card object and not a source? Currently I'm creating a Charge using the customer id and the card id as the source. What's really the difference between using cards as sources and creating Source object over the api?

**Comment by remi-stripe** [comment]
@bigzoo Card objects and Source objects would both be returned in the `sources` array, they would just have a different value for `object`. For a Card the type would be `card` and for a Source it would be `source` instead.

Since you use tokens at the moment, you'd only ever get Cards and you can ignore Sources (the object, not the name of the property, sorry if this is confusing).

**Comment by bigzoo** [comment]
@remi-stripe I understand though it was a little confusing at first. So I guess that the source parameter required when creating a Charge really doesn't explicitly mean a source object id but can be either that or a card id or just the token itself?

**Comment by remi-stripe** [comment]
@bigzoo Exactly!

**Comment by dylantrooien** [comment]
/** @var \Stripe\Source $Source */
$Source = $Customer->sources->retrieve($card);
$Source->detach();
Gives error : Attempted to call an undefined method named "detach" of class "Stripe\Card".

/** @var \Stripe\Source $Source */
 $Source = $Customer->sources->retrieve($card);
 $Source->delete();
Works but delete() is depreciated 

using "stripe/stripe-php": "^6.23",

**Comment by ob-stripe** [comment]
@dylantrooien This is the same issue that @remi-stripe explained above: in your code, `$Source` is an instance of `\Stripe\Card`, not `\Stripe\Source`. `delete()` is not deprecated on `\Stripe\Card`.
