### ISSUE TITLE
Docs should explain why cards can only be retrieved through their customers

### ISSUE THREAD

**Issue by alexweissman** [stripe/stripe-php#459]
I got a nasty surprise when I discovered that you can only retrieve a card via the owning Customer (see https://github.com/stripe/stripe-php/blob/master/lib/Card.php#L75-L78).

I don't like surprises. This forced me to redesign my data model to include customer ids alongside the card ids so that I can retrieve and charge them.

At the very least, this should be explained in the documentation. Is it a technical limitation on Stripe's side? Is it supposed to be a security feature? I shouldn't be able to retrieve a card that belongs to a customer who isn't mine, anyway. The docs seem to assume that everyone automatically decides to store Customer ids along with Card ids.

**Comment by remi-stripe** [comment]
@alexweissman Cards live under the Customer objects and so they can only be retrieved through that customer. This customer id is part of all the URLs used for the Card APIs but I agree it could be made clearer.

The Card object has existed for many years and for now is linked to the Customer object. A year or so ago, we shipped a new abstraction for payment methods called Sources. This allows to group all payment methods under one object instead of having disparate abstractions like Cards and Bank accounts.

The Source object can be retrieved directly by its id without having to also store the customer id so it would meet your requirements. You can read more about this in the docs here: https://stripe.com/docs/sources/customers

**Comment by alexweissman** [comment]
Ah, interesting, thanks for pointing that out! So is there an "is-a" relationship between Card and Source? I.e., is a Card a subtype of Source now? Or would I need to start explicitly creating `src_` objects?

By the way, is there a better place to open up issues concerning the documentation?

**Comment by remi-stripe** [comment]
@alexweissman Card and Source are two entirely separate objects. Card is the old representation which was built at a time when we only supported Card payments. We then added Bank Account objects for ACH debits.

When we started added more payment methods (3D Secure, SEPA debits, etc.) we wanted to add a common abstraction on top of all of those and that's when we shipped Sources.

I would recommend using Sources moving forward in your case and dropping Tokens and Cards completely based on the datamodel you wanted to rely on.

For follow up questions, I'd recommend talking to our support team directly: https://support.stripe.com/email
