### ISSUE TITLE
Property to automatic cancel a plan subscription in specific date

### ISSUE THREAD

**Issue by somoza** [stripe/stripe-php#518]
If some customer pays for a service that lasts 4 months I need to specify a caducity date for the subscription plan, so I don't have to develop tasks or cronjobs and store subscriptions in my local DB.

**Comment by remi-stripe** [comment]
@somoza Today, subscriptions renew automatically until you explicitly cancel them. If you want to have a subscription that lasts only 4 months, you need to implement this on your end. The idea would be to use webhooks and you can read our recipe here: https://stripe.com/docs/recipes/installment-plan

**Comment by ronlinet** [comment]
There is a ‘cancel_at’ parameter in the ‘[create](https://stripe.com/docs/api/subscriptions/create)’ method. 
According to this post it has been [around since at least 2019](https://stackoverflow.com/questions/49431030/stripe-cancel-subscription-at-specific-date).   
This is how it looks in stripe 7.128 
```
$this->stripeClient->subscriptions->create(
[           
            'customer' => 'xxxxx',
            'cancel_at'=> timestamp,  
            'items' => [
                [   
                    'price_data' => $price_data
                ],
            ],
]; 
```
