### ISSUE TITLE
UBlock Origin Seems to Interfere With Stripe Elements & Stripe PHP

### ISSUE THREAD

**Issue by vegaskev** [stripe/stripe-php#528]
Starting some time today, stripe elements started throwing errors with U Block Origin Enabled.

When I disable UBlock Origin for the site, the errors disappear and processing works fine.

NOTE: This may have absolutely nothing to do with the stripe-php.  The issue might solely be with the stripe elements call on page load (most likely)

Thanks in advance.

<img width="1440" alt="ublockorigin-stripe-issue" src="https://user-images.githubusercontent.com/2360033/46328409-e1a45680-c5bb-11e8-94c8-722e98741b50.png">

**Comment by ob-stripe** [comment]
Hi @vegaskev. Indeed, this issue is most likely related to Elements and not to the stripe-php library, so I'm going to close the issue. I recommend you reach out to support at https://support.stripe.com/email to report this problem.

In your message, you should mention which browser you're using, and if you're using any non-default block list in uBlock Origin -- default block lists should not affect Stripe.js / Elements.

**Comment by sambokai** [comment]
Related: https://github.com/stripe/react-stripe-elements/issues/222

They had the same problem with `react-stripe-elements` and `AdBlock`
