### ISSUE TITLE
Request-Id is now lowercase

### ISSUE THREAD

**Issue by ruudk** [stripe/stripe-php#529]
After upgrading from v6.10.0 to v6.19.1 I noticed that the `Request-Id` header does not exist anymore. Instead, you have to use `request-id`. 

Why was this breaking change not documented and included in a new major?

**Comment by ob-stripe** [comment]
Hi @ruudk, thanks for the report and sorry for the trouble. It turns out this was an unforeseen side-effect of enabling HTTP/2 in the library (cf. #494).

In HTTP/2, all headers are in lowercase. HTTP headers are supposed to be case-insensitive, but since the headers are copied in a regular PHP array, the keys are case-sensitive :/

We'll work on a fix and update here once it's released.

**Comment by ob-stripe** [comment]
Fixed in 6.19.2. Headers can now be accessed regardless of case.

Feel free to reply here if you're still encountering issues after upgrading.

**Comment by ruudk** [comment]
Thanks for the fast fix!! 👏
