### ISSUE TITLE
Can't Retrieve Products on Connected Accounts

### ISSUE THREAD

**Issue by Stokoe0990** [stripe/stripe-php#533]
The following line of code will retrieve up to the first 100 plans on a Stripe Connect Account.
`$s_plans = Plan::all(['limit' => 100], ['stripe_account' => $stripe_connect_id]);`

Running the exact same line of code against Products doesn't retrieve any.
`$s_products = Product::all(['limit' => 100], ['stripe_account' => $stripe_connect_id]);`

The return is
`Collection {#1041 ▼
  #items: []
}`

Upon inspecting the retrieved plans, I got a Product ID, running...
`Product::retrieve($id, ['stripe_account' => $stripe_connect_id]);`
...doesn't get anything either.

**Comment by remi-stripe** [comment]
@Stokoe0990 If you look at the code in the library for [Plans](https://github.com/stripe/stripe-php/blob/master/lib/Plan.php) and [Products](https://github.com/stripe/stripe-php/blob/master/lib/Product.php) you can see they are identical.

I don't think the issue is with our PHP library or the implementation. My guess is that you are on an old API version from before the Plan/Product split. Because of this, you can only retrieve Plans and not Products because you don't have any. We created some behind the scenes for you when we introduced the split but the API would not return those unless you upgraded to at least [2018-02-05](https://stripe.com/docs/upgrades#2018-02-05). You can try quickly with the `Stripe-Version` [header](https://stripe.com/docs/api#versioning) for example.
