### ISSUE TITLE
Ensure library can be loaded safely in a shared environment, e.g. Wordpress

### ISSUE THREAD

**Issue by andyyoung** [stripe/stripe-php#54]
Reported by Bob C. Do something to help minimise chances that multiple developers try and include different versions / copies of the library, causing fatal error due to class collision.

**Comment by bkrausz** [comment]
See my previous comment, I think namespaces will make this easier, but generally this isn't something PHP can easily solve for you. Closing this out unless there's further discussion to be had on it.

**Comment by bluestarstudios** [comment]
7 years later, this is still an issue. Example:

1. Plugin A integrates version 6.43.1 of the Stripe PHP library using an autoloader.
2. Plugin B was smarter to check if the class exists first, but since it does (was loaded by Plugin A) it doesn't load it's own version 7.52.0.  Now plugin B ends up generating various notices/warnings/errors because it's being forced to interact with an older version of the Stripe PHP library.

Adding an ability for devs to easily namespace their copy of the Stripe library would allow them to embed each of their versions without causing conflicts, allowing `\PluginAStripeLib\Stripe` to run alongside `\PluginBStripeLib\Stripe`.

I don't have exact knowledge of how this should be accomplished, but want to open up the conversation, particularly since nowadays [80% of the WordPress market is on PHP version 7 or greater](https://wordpress.org/about/stats/).

**Comment by remi-stripe** [comment]
@bluestarstudios Thanks for reporting this again. It's definitely something we want to fix, but it's not easy to fix in PHP. If anyone in this thread has advice on how to approach this, let us know!
