### ISSUE TITLE
error => Unexpected error communicating with Stripe. (Network error [errno 35]: SSL version range is not valid.)

### ISSUE THREAD

**Issue by arkhalid1986** [stripe/stripe-php#545]
Hello,

I am getting problem stripe error is showing below.

error => Unexpected error communicating with Stripe.  If this problem persists, let us know at support@stripe.com.

(Network error [errno 35]: SSL version range is not valid.)

I have check the TLS via this file tls_test.php and that's what i get below.

OS: Linux
uname: Linux cloudserver-01 2.6.32-042stab130.1 #1 SMP Tue May 22 09:19:34 MSK 2018 x86_64
PHP version: 7.2.11
curl version: 7.62.0
SSL version: NSS/3.36
SSL version number: 0
OPENSSL_VERSION_NUMBER: 1000105f
TLS test (default): TLS 1.2
TLS test (TLS_v1): TLS 1.0
TLS test (TLS_v1_2): Error! errno = 35, msg = SSL version range is not valid.

Please let me know how to resolve this issue?

**Comment by remi-stripe** [comment]
@arkhalid1986 Usually, this is due to a bad PHP installation. Often it means that your version of PHP was built with a different version of curl and/or openssl and so it does not expect the setting we're trying to enable to switch to TLS 1.2.

The most common solution for this issue is to uninstall all three and reinstall the latest version cleanly. Otherwise there are some instructions on our readme that might help: https://github.com/stripe/stripe-php#ssl--tls-configuration-option

**Comment by ob-stripe** [comment]
According to the script's output, your requests should work provided that:
- you are using a recent version of stripe-php (>= 4.0)
- you are **not** manually setting the `CURLOPT_SSLVERSION` option as illutrated in https://github.com/stripe/stripe-php#ssl--tls-compatibility-issues

Can you let us know which exact version of stripe-php you're using? If you're using an older version, can you try upgrading to the latest (or at least to 4.0)?

**Comment by ob-stripe** [comment]
Closing due to age, but feel free to reply if you're still having trouble.
