### ISSUE TITLE
Network/Host errno 6

### ISSUE THREAD

**Issue by EatonZ** [stripe/stripe-php#560]
PHP 7.2.12 (Windows)
Stripe PHP 6.17.0

Ever since I have been using this Stripe library (been using it a long time), I have been getting this error at random times:
```
Could not connect to Stripe (https://api.stripe.com/v1/customers/xxx).  Please check your internet connection and try again.  If this problem persists, you should check Stripe's service status at https://twitter.com/stripestatus, or let us know at support@stripe.com.

(Network error [errno 6]: Could not resolve host: api.stripe.com)
```

This pretty much only happens when retrieving a customer object. I wanted to ask if this could possibly be a bug in the library. No other code on my server ever throws network errors like this, and the Stripe Status never shows downtime when these errors get logged. It's gotten to the point where seeing this in my logs has become annoying and I am concerned it may be causing long load times for customer account pages.

This error usually happens at least once a week. I am open to anything that may help narrow down the problem or at least output some additional information about the problem when it occurs.

**Comment by remi-stripe** [comment]
@EatonZ The fact that it only happens when retrieving a customer is strange but is likely just a coincidence. This error is quite specific here and indicates that your server can not resolve api.stripe.com which means that it's a DNS issue. This is really more of a transient connection issue due to something on your server or ISP I would say. Here, I would recommend contacting the support team of your host provider to ask for help debugging this as they would likely be able to monitor this on their end and figure out what could be causing this.

I'm going to close this out as I don't think it could be a bug in the library itself, especially as you have been using this for a long time. If you get more details, I would recommend following up with our support team instead: https://support.stripe.com/email

**Comment by eclyptox** [comment]
@EatonZ did you solved this issue? I'm facing same issue and only some customers. I have tried API with curl and I have not getting this error.
Thanks

**Comment by EatonZ** [comment]
@eclyptox I actually haven't gotten this error again since I posted this issue. I haven't updated the stripe-php copy on my server, but I do keep my PHP version up to date. Maybe that helped, since new PHP releases sometimes include updated curl versions.

It also could have just been issues with the host network that have been resolved. I don't think it's an issue with this library.
