### ISSUE TITLE
Missing Event constant: SUBSCRIPTION_SCHEDULE_ABORTED

### ISSUE THREAD

**Issue by jimyaghi** [stripe/stripe-php#563]
I'm using the Stripe Events webhooks api to manage subscription based sales. The documentation lists an event subscription_schedule.aborted (specifically referring delinquent subscriptions) but this is not found in the library constants as \Stripe\Event::SUBSCRIPTION_SCHEDULE_ABORTED similar to others in the same family.

I wonder if this was merely an oversight or if the event is no longer fired or is even replaced with another event.

Also, any idea what a "Subscription Schedule" object is? Clicking in the documentation it appears the link is broken or incorrect. https://stripe.com/docs/api/events/types see here under subscription_schedule.* family of events

~jim

**Comment by brandur-stripe** [comment]
It's definitely an oversight — those events are stilled fired. I added some new constants in #564.

> Also, any idea what a "Subscription Schedule" object is? Clicking in the documentation it appears the link is broken or incorrect. https://stripe.com/docs/api/events/types see here under subscription_schedule.* family of events

Thanks for noticing that. I believe this feature is still under development and that the event types list is exposing it a bit early because it's generated automatically. I'm going to following up with our Billing team internally to see what the best course of action for this is.
