### ISSUE TITLE
Issue attaching cardholder info to source

### ISSUE THREAD

**Issue by GabotronES** [stripe/stripe-php#596]
Hi everybody, I'm trying to attach the name of the cardholder to a newly created source with stripe's elements.js.

However when I submit my form I get the following error:
```
Received unknown parameter: name
```
I attach an object with that info in the createSource function, like this:
```
$('#payment-form').submit(function(e) {
        console.log('submitted');
        e.preventDefault();

        stripe.createSource(cardNumberElement, { name: self.cardHolder }).then(function(result) {
            if (result.error) {
                self.cardErrors = result.error.message;
            } 
            else {
                stripeSourceHandler(result.source);
            }
        });
    });
```
Is there any other way to store cardholder name into sources?

**Comment by remi-stripe** [comment]
@GabotronES Sources don't have the name parameter. Instead, it lives under `owner[name]`. You can see an example here: https://jsfiddle.net/8t73suLp/

I'm also closing this issue because it's a question about Elements and unrelated to stripe-php. Issues on this repo should be limited to bugs with our PHP library instead.

If you have a follow-up question, don't hesitate to reach out to our support team instead: https://support.stripe.com/contact?email=true
