### ISSUE TITLE
Trailing slashes issue

### ISSUE THREAD

**Issue by shawnspaul** [stripe/stripe-php#598]
Unrecognized request URL (GET: /v1/customers/{customer_id}/sources/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.

**Comment by remi-stripe** [comment]
@shawnspaul This is not an issue with the library. This is due to the fact that you are retrieving a source (or a card) but passing an empty string as the id in the parameter. 

I'm going to close this out but don't hesitate to contact our support team if you have more questions [here](https://support.stripe.com/contact?email=true)
