### ISSUE TITLE
Card expired exception but I also recharge success.

### ISSUE THREAD

**Issue by tkloespikgit** [stripe/stripe-php#620]
When I try to create a charge , but I got the exception says " Your card is expired", The customer’s money is still charged.

**Comment by paulasjes-stripe** [comment]
This isn't due to the Stripe PHP bindings, but an integration issue. Please contact support for help with this: https://support.stripe.com/contact

**Comment by hondaman900** [comment]
@tkloespikgit , did you ever get this resolved with Strip? I am having the same issue where my test client enters a card with good expiration date, the card shows as accepted, but Stripe API returns a "Your card has expired" error (the prior card on the customer's record in Stripe is expired, but not the one used for this transaction). The customer Stripe account shows the purchase, but my app never got the confirmation and now they're out of sync. This is particularly bad when my customer upgrades a subscription, as thereafter Stripe says "Noting to invoice" because it thinks he's already upgraded whereas my app never upgraded him because the transaction bombed. Any help is very welcome.

**Comment by remi-stripe** [comment]
@hondaman900 I'd recommend reaching out to the support team for help on this. This is quite an old issue that was already redirected to the support team so that would be the best next step
