### ISSUE TITLE
Call to undefined method Stripe\Account::listPersons()

### ISSUE THREAD

**Issue by hullo-rikard** [stripe/stripe-php#622]
Hi,

I do have some problems retrieve either a singel person connected to an account or a list of all persons connected to an account. I have not tested this live, only in test mode. I have tried with older Stripe PHP library versions without success.

PHP-version: 7.1.23
Stripe PHP library: 6.31

`$persons = \Stripe\Account::listPersons($accountID);`
**Generates error:** Fatal error: Uncaught Error: Call to undefined method Stripe\Account::listPersons()

And

`$account = \Stripe\Account::retrieve($accountID);`
`$person = $account->persons->retrieve($personID);`
**Generates error:** Fatal error: Uncaught Error: Call to a member function retrieve() on null in

**Comment by remi-stripe** [comment]
@hullo-rikard The first error is because you need to use `allPersons` instead of `listPersons`. It looks like the example in the doc is incorrect so I'll flag internally so that it gets fixed.

The second error is similar. There is no `persons` hash on the `Account` resource so that would not work.

If you have any follow up questions, don't hesitate to reach out to our support team: https://support.stripe.com/contact?email=true
