### ISSUE TITLE
Duplicate Cards

### ISSUE THREAD

**Issue by xinthose** [stripe/stripe-php#747]
PHP library version 7.0.0

Hello.  Is it expected behaviour for `\Stripe\Customer::createSource`  to add duplicate cards (same number, CVC, ZIP, address, name, etc.) to a customer?  It is hard to find duplicates because you have to check more than just the card's fingerprint.  Likewise, I cannot create a charge on a Customer without first saving their card, thus leading to the repetitive add.  

![Capture](https://user-images.githubusercontent.com/12835202/65640430-fc7f9000-dfaf-11e9-84a8-84b3c8e1a091.PNG)

**Comment by ob-stripe** [comment]
Hi @xinthose. Yes, the API doesn't automatically deduplicate cards. You can use the [`fingerprint`](https://stripe.com/docs/api/cards/object#card_object-fingerprint) if you want to do that yourself.

Closing since this isn't an issue with stripe-php but rather with the API itself. If you have followup questions, I recommend you reach out to Stripe's support at https://support.stripe.com/email.

**Comment by xinthose** [comment]
@ob-stripe  OK.  Thank you sir.
