### ISSUE TITLE
InvoiceItem::create() - You may only specify one of these parameters: amount, quantity

### ISSUE THREAD

**Issue by hsharma-lsquared** [stripe/stripe-php#777]
I am calling a function InvoiceItem::create(), just before subscription creation for one time product purchase with subscription, so I am calling the below function:

$invoice = \Stripe\InvoiceItem::create([
	'amount' => $totalAmount,
	'currency' => CURRENCY_CODE,
	'customer' => $customerId,
	'description' => $paramArr['description'],
	'metadata' => $metaDataArr,
	'quantity' => $quantity
]);

But it returns error like this:

"invalid_request_error"
You may only specify one of these parameters: amount, quantity

Request Id:
req_ada8vltwA1YQU8
req_Gh6SibLApANcoZ

SDK/API Version: 2019-08-14

**Comment by remi-stripe** [comment]
@hsharma-lsquared Github issues should be limited to bugs in the libraries. This question is more about the API itself so I'm going to close. To get support on this it's best to write to our support team https://support.stripe.com/contact

The problem though is that you can't pass `quantity` and `amount` together. `amount` is for the total amount of the invoice item. If you want to handle `quantity` you need to pass [`unit_amount`](https://stripe.com/docs/api/invoiceitems/create#create_invoiceitem-unit_amount) with it instead of `amount`.
