### ISSUE TITLE
Remove element from Charge collection. 

### ISSUE THREAD

**Issue by ronlinet** [stripe/stripe-php#779]
What is right approach to remove an element from a Charge collection?
The PHP `unset($charge)`  doesn't do the trick ..
```

            $charges = \Stripe\Charge::all(["limit" => '10']);

            foreach ($charges as $key => $charge )
            {
                if(  $charge->amount < 1 )
                {            
                    unset($charge);
                }    
                     
            }
```

**Comment by remi-stripe** [comment]
@ronlinet I'd recommend building a separate list of charges that you want to keep track of in a separate array instead of trying to mutate the collection we're returning as that won't work.

**Comment by ob-stripe** [comment]
Hi @ronlinet. In theory, you could remove element from the collection like this:

```php
unset($charges->data[$key]);
```

However, it's almost never a good idea to modify an array while iterating on said array. In addition, as @remi-stripe pointed out, you probably don't want to be modifying the `\Stripe\Collection` object directly as this is unlikely to yield the results you want.

Closing since this is not an issue with the library, but feel free to reply.

**Comment by ronlinet** [comment]
@ob-stripe I am just migrating all stripe payment to my own db for reporting purposes and I need a quick hackish solution to avoid redundant entries. It is a temporary fix, once migration done I will use SQL to deal with this. Thank you for your quick feedback the `unset($charges->data[$key]);` was what I was looking for.
