### ISSUE TITLE
Unable to retrieve sources using the sdk

### ISSUE THREAD

**Issue by haid45** [stripe/stripe-php#782]
I am unable to retrieve sources for customers.
my code is as follows 
`$data['cards'] = \Stripe\Customer::allSources(
                    $tokens['stripe_client_id']
                );`

and this is the response I am getting

 `   object: "list"
    data: []
    has_more: false
    url: "/v1/customers/41/sources"`

any help would be highly appreciated

**Comment by remi-stripe** [comment]
@haid45 This should return the list of cards or sources on this customer. My guess is that you are not using those and instead maybe are using PaymentMethods instead which is the new API. If so, you want to use https://stripe.com/docs/api/payment_methods/list instead

I'd recommend reaching out to our support team as it would require investigating your current integration and setup otherwise to get more details. You can contact them here: https://support.stripe.com/contact

**Comment by haid45** [comment]
Thank you kindly for your prompt response, as you guessed, it was due to the PaymentMethods Api being used.

I am now able to retrieve the stored cards
