### ISSUE TITLE
Mock stripe curl for failure,exceptions & success

### ISSUE THREAD

**Issue by ujwaldhakal** [stripe/stripe-php#822]
This library clearly does not state the use of mock for request .
I wanted to fail stripe with certain exception so that i wanted to check how my underlying wrapper works accordingly but couldnt find docs nor i could tap into source code

**Comment by ob-stripe** [comment]
You could mock requests by writing a custom HTTP client class that implements the [`\Stripe\HttpClient\ClientInterface`](https://github.com/stripe/stripe-php/blob/d7d11658defa08ca8f6fc6668c745aaa67f56bdf/lib/HttpClient/ClientInterface.php) interface. Something like this:

```php
class MockClient implements \Stripe\HttpClient\ClientInterface
{
    public $rbody = '{}';
    public $rcode = 200;
    public $rheaders = [];

    public function request($method, $absUrl, $headers, $params, $hasFile)
    {
        return [$this->rbody, $this->rcode, $this->rheaders];
    }
}

$mockClient = new MockClient();
\Stripe\ApiRequestor::setHttpClient($mockClient);

// Configure the mock client to return an error
$mockClient->rbody = json_encode([
    'error' => [
        'type' => 'invalid_request',
        'message' => 'This is a fake error.'
    ]
]);
$mockClient->rcode = 400;

// Trigger an API request and catch exception
try {
    \Stripe\Charge::all();
} catch (\Stripe\Exception\ExceptionInterface $e) {
    // This will output "This is fake error."
    echo $e->getMessage();
}
```

Does this help?

**Comment by ob-stripe** [comment]
Closing, but feel free to reply!

**Comment by ujwaldhakal** [comment]
Thanks @ob-stripe

**Comment by fideloper** [comment]
Hello from over a year later! Hopefully someone can help here, as I'm trying to accomplish a very similar thing here (mocking the `ClientInterface` so I don't make calls to the Stripe API in my tests).

When I mock out the HTTP client (even by extending the CurlClient and over-writing the `request()` method, rather than implementing the `ClientInterface` interface), I get this error:

```
testing.ERROR: Laravel\Cashier\Checkout::__construct(): Argument #2 ($session) must be of type Stripe\Checkout\Session, Stripe\StripeObject given,
```

I am wondering why just this one change of mocking the client is results in a `StripeObject` being given as a result of calling `$stripeClient->checkout->sessions->create([...])` instead of the `Stripe\Checkout\Session` object I get when not mocking the `HttpClient`.

Any pointers? I can't seem to figure this one part out.

**Comment by fideloper** [comment]
More code diving figured this out, sorry to bother! I had some extraneous code that returned incorrect JSON from the mock, so it didn't map to the Session object correctly.

**Comment by raisaubhagya** [comment]
> 
i am getting this error. 
No API key provided.  (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)".  You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.
