### ISSUE TITLE
Type annotations are too generic

### ISSUE THREAD

**Issue by MidnightDesign** [stripe/stripe-php#859]
Many type annotations (like the one for `PaymentMethod#$card`) used to just say `mixed` - which wasn't very good. @ob-stripe [committed](https://github.com/stripe/stripe-php/commit/122a618f006c27dbcdd1f0b16575330111e32d1c) [many](https://github.com/stripe/stripe-php/commit/a87db72c41d1011600d5af272feec81cfa448374) [updates](https://github.com/stripe/stripe-php/commit/67a116e89b9d579ded909b83f6556a5eac25285c) in the last couple of weeks and months adding better types. But they are still way too generic. For example, shouldn't `PaymentMethod#$card` be of type `Card` instead of just `StripeObject`?

Also, in our code, we're checking if for nullability of many fields - which tells me that they must have been nullable at some point - which the type annotations also don't reflect.

**Comment by ob-stripe** [comment]
Hi @MidnightDesign, thanks for the feedback!

With a few exceptions (that we're working on fixing), the type annotations are now about as precise as we can make them given the current state of the library.

> For example, shouldn't `PaymentMethod#$card` be of type `Card` instead of just `StripeObject`?

The `Card` class represents https://stripe.com/docs/api/cards/object objects. `PaymentMethod#$card` represents the [`card`](https://stripe.com/docs/api/payment_methods/object#payment_method_object-card) hash of [`payment_method`](https://stripe.com/docs/api/payment_methods/object) objects, which doesn't have exactly the same structure, and for which the stripe-php library does not have an explicit class.

> Also, in our code, we're checking if for nullability of many fields - which tells me that they must have been nullable at some point - which the type annotations also don't reflect.

I assume you're also referring to `PaymentMethod#$card` and similar fields. Strictly speaking, those fields are optional, not nullable, i.e. the JSON response returned by Stripe's API will either include the key with a non-null value, or not include the key at all -- it will never return `"card": null`. The proper way to access those fields is to first check the value of the [`type`](https://stripe.com/docs/api/payment_methods/object#payment_method_object-type) field, which tells you which key will be present.

We decided not to tag those fields as nullable because it conveys the wrong idea: trying to access them when not set will indeed return `null`, but it will also log an error (see https://github.com/stripe/stripe-php/blob/master/lib/StripeObject.php#L169-L170).

Unfortunately PHPDoc does not have a notation for optional fields. We're planning on simply adding a description to the PHPDoc type, something like this:
```
* @property \Stripe\StripeObject $card only present if $type=='card'
```

Would that work for you?

**Comment by MidnightDesign** [comment]
Perfect, thanks for clearing that up! Additional descriptions would be great, yes.
