### ISSUE TITLE
List pagination total count

### ISSUE THREAD

**Issue by nomadme** [stripe/stripe-php#878]
Currently it is not possible to see total number of counts in the list object when there is pagination needed. 

It would be great if we have this information that it will aid UX, when someone needs to paginate through lot of invoices.

**Comment by brandur-stripe** [comment]
Hey @nomadme, we used to offer this feature, but generating a total count along an index in any database is an expensive operation (unless you cache a count separately, the only way to build one is to iterate the entire index), and therefore we don't make it available anymore because it made requests extremely prone to timeouts for any large collection.

It's possible that we'll do some kind of total count caching in the future and be able to provide this once again, but I wouldn't bank on it for now.

**Comment by nomadme** [comment]
@brandur-stripe Thanks for the response. I totally understand that this expensive operation even for my end, we don't want to iterate the entire index as well, that is why the pagination is therefore, isn't it!

I see this information is readily available from the `dashboard/invoices?customer`, so I think this is something you guys already doing it on your end. 
[https://www.dropbox.com/s/t1xippxpbim1vom/Screenshot%202020-02-14%2012.25.14.png?dl=0](url)

**Comment by brandur-stripe** [comment]
> I see this information is readily available from the `dashboard/invoices?customer`, so I think this is something you guys already doing it on your end. 

Yep, we definitely do. As noted above though, we're slowly killing off use of this feature due to the high risk of timeouts (or just long requests even if they don't timeout) for large collections. Eventually even those Dashboard pages will probably just read "many results" if you have a non-trivial number of objects.

**Comment by nomadme** [comment]
I see...

> unless you cache a count separately
would you guys consider doing caching this information like you suggested earlier?

**Comment by brandur-stripe** [comment]
> would you guys consider doing caching this information like you suggested earlier?

Absolutely, but it's a non-trivial feature to build out, and to my knowledge no one is working on it right now.

Let me remind you that you can also build this same count caching strategy on your end!

**Comment by nomadme** [comment]
isn't it makes less sense as to have this cache on the API consumer end? Since the customer in stripe, can have invoices generated even directly from the Stripe dashboard by customer support, or sales person? which in the case that the app will have no direct involvement in creating invoice.

**Comment by remi-stripe** [comment]
@nomadme In that case you would use Webhooks to keep track of what happens in your account: https://stripe.com/docs/webhooks

**Comment by vidalem** [comment]
Hi there, thanks for the info here.
Is there any update about implementing a cached total count of a customer invoices list?

regards

**Comment by remi-stripe** [comment]
@vidalem No update to share per se. We don't plan to offer a cached count in our List APIs in the future either. You could look at the Search Invoice API instead
* https://stripe.com/docs/api/invoices/search
* https://stripe.com/docs/search#query-fields-for-invoices
