### ISSUE TITLE
Hi, Finding issue of Form not submit In Custom PHP

### ISSUE THREAD

**Issue by marksingh07** [stripe/stripe-php#891]
Hi, 
  I am trying to add stripe payment in my custom PHP code and finding error  
 **Uncaught TypeError: $form.get(...).submit is not a function
    at stripeResponseHandler**

  url of Form 
  https://floristway.com/florist/payment.php

unable to find solution , please tell solution
using v2

![image](https://user-images.githubusercontent.com/50451113/75890716-c1359700-5e54-11ea-8e51-2e174dc93b13.png)

Thank you

**Comment by remi-stripe** [comment]
@marksingh07 Github issues should be limited to bugs with the stripe-php library itself. The screenshots you shared show a Javascript error, likely because you are trying to submit an element that is not a form. I'd recommend reaching out to our support team instead: https://support.stripe.com/contact

**Comment by marksingh07** [comment]
Okay,
Thank you
