### ISSUE TITLE
tax_rates or default tax_rates is not accepted by /v1/customers/:id/subscriptions endpoint

### ISSUE THREAD

**Issue by lositojason** [stripe/stripe-php#917]
When I add a 'default_tax_rates' or 'tax_rates' in $customer->subscriptions->create arguments, it says unknown params even if says in the API that you can add them. 'tax_percent' works but I need any of the two and not tax_percent.

**Comment by remi-stripe** [comment]
@lositojason Thanks for the report! This isn't a bug with the library itself and is simply a limitation of the API. We only support `tax_rates` and `default_tax_rates` on the new API method via `/v1/subscriptions` and `\Stripe\Subscription`. We recommend upgrading your code to that instead of relying on the nested sub-list of subscriptions for creation as this has been live for multiple years already.

I do see how it would be easier if both endpoints worked the same way though and I've flagged it internally as a potential future improvements!
