### ISSUE TITLE
Can't update InvoiceLineItem metadata

### ISSUE THREAD

**Issue by poisa** [stripe/stripe-php#929]
If you look at the `InvoiceLineItem` docs for the PHP language (https://stripe.com/docs/api/invoiceitems/update?lang=php) the example there is doing exactly what I need to do, which is to update line item metadata:
```php
\Stripe\Stripe::setApiKey('<snip>');

\Stripe\InvoiceItem::update(
  '<id>',
  ['metadata' => ['order_id' => '6735']]
);
```

Yet when I issue the request, I get: 

```json
{
  "error": {
    "message": "When passing an invoice's line item id, you may only update `tax_rates`.",
    "type": "invalid_request_error"
  }
}
```

The question is, how can I update a line item metadata without passing it's id?

**Comment by remi-stripe** [comment]
@poisa The API you're calling is to update an *invoice item*. This represents one of invoice items you create as pending so that they roll into the next invoice automatically. Those are different from *invoice line item* which is a line item on an invoice after it's been created. Those can not be mutated the same way.

I'm sorry that this might look confusing but it's not possible to set metadata on an invoice line item that way. You should put the metadata on the Invoice itself instead.

If it helps, we're actively working on a new API called `LineItem` that will work on all resources, including `Invoice` to replace all those classes and unify them in one canonical path. This is not something ready yet but it will make things easier in the future.

If you have any follow-up questions, I'd recommend reaching out our support team instead as Github issues are limited to bugs and feature requests for the library itself. You can contact them here: https://support.stripe.com/contact
