### ISSUE TITLE
Identifier definition

### ISSUE THREAD

**Issue by stingus** [stripe/stripe-php#940]
It would really help to have the $id defined for all Stripe objects, instead of the @property annotation. This prevents us from using Stripe objects as DTO resources in api-platform, since we cannot assign the identifier to a 'virtual' property which is only accessed via magic methods.

I'm not very familiar with the library, but maybe this is something that can be taken into account?

**Comment by richardm-stripe** [comment]
Hi @stingus, thanks for the suggestion.

My gut reaction is that this probably isn't something we would support. The public interface of stripe-php is the method invocations and property accesses. If api-platform cares whether `->id` is a magic method or a declared property, it must be using reflection and we don't usually consider the shape of stripe-php under reflection to be a part of the public interface because that would be too limiting, and we don't want to encourage users to become dependent on these details.

I suggest wrapping the Stripe object in a class that has the shape you need.

That said, would you mind elaborating a little more on your use case -- what exactly it means to use a Stripe object as a DTO resource in api-platform and why this is useful?

**Comment by stingus** [comment]
Hey @richardm-stripe, thanks for the info. Here's the scenario that lead to this question.

We're using an api-platform service, as an interface between our backend and Stripe. We have our own entities which should be translated to Stripe entities upon sending requests to Stripe, and vice-versa when responding. Of course, there are multiple ways to accomplish this behavior, but the most suited is using [api-platform's DTOs](https://api-platform.com/docs/core/dto/). In this case, Stripe entities will be the ones defined in api-platform's configuration and our own entities will be converted to / from using Input and Output transformers.

### The problem
API platform relies on an entity identifier. This is `id` by default, but can be anything we choose. In this case, Stripe's `id` naming fits the default value expected by api-platform. But being a magic method, it triggers an error because api-platform cannot find the actual property. My guess is that it relies on property-access and Reflection, but I didn't go that far with the debug. Thing is, it doesn't recognize the property as an identifier, but when I altered a Stripe entity class and declare it there, it worked. Error is `Invalid identifier value or configuration.`

### Wrapper workaround
That was my second thought as well, and to give you more context, we're also using a custom [DataProvider](https://api-platform.com/docs/core/data-providers/) in place. I've created a wrapper class (let's call it DtoCustomer) over Stripe\Customer and declared one property, `$id`. The CustomerDataProvider should fetch the customer from Stripe and pass it to the output transformer. For this magic to work, the DataProvider must return an instance of DtoCustomer, and not Stripe\Customer, because api-platform resource definition is for DtoCustomer, and not Stripe\Customer. Bottomline, that's the reason why I can't use a wrapper. If I would convert the Stripe\Customer to the DtoCustomer in the CustomerDataProvider, it would defeat the purpose of using the transformation tools provided by api-platform.

Not sure if all this makes sense, just let me know which part is confusing. Hope some of it is clear :) If it would help, I can set up a small project based on the above and share it with you.

**Comment by stingus** [comment]
Closing this, it's a request narrowed on a very particular use-case.
