### ISSUE TITLE
Fatal error: Uncaught (Status 400) (Request req_qp5ygScTPZF6Jk) This value must be greater than or equal to 1. thrown in C:\xampp\htdocs\vendor\stripe\stripe-php\lib\Exception\ApiErrorException.php on line 38

### ISSUE THREAD

**Issue by The1uchiwa** [stripe/stripe-php#943]
hello everyone :
**php version** :7.4.2
**stripe version** :7.36.1
_i used stripe api many time to include payment modal
and i don't got any error because it's work normally
but today ,I got the following error when I create a charge and i don't know where is the problem_ :

**### Fatal error: Uncaught (Status 400) (Request req_qp5ygScTPZF6Jk) This value must be greater than or equal to 1. thrown in C:\xampp\htdocs\vendor\stripe\stripe-php\lib\Exception\ApiErrorException.php on line 38**

Please help me to find out the solution and thanks you

**Comment by richardm-stripe** [comment]
Hello @The1uchiwa,

The most likely cause of this error is that when you are calling the Charge create method, you are somehow passing `0` for the "amount" parameter. I would check the code in between your payment modal and the Charge create method to make sure "amount" is being set as you expect.

Since I don't think this is a bug with the stripe-php library itself, I recommend reaching out to our support team, which you can contact here: https://support.stripe.com/contact

**Comment by AkramBiblo** [comment]
Dear concern,
I am trying to test stripe payment using localhost and getting the following error. Kindly advice how I can get rid of this error...
Regards.

Fatal error: Uncaught (Status 400) (Request req_tsihakNBoHhF6u) Invalid object thrown in C:\xampp\htdocs\php\stripe\vendor\stripe\stripe-php\lib\Exception\ApiErrorException.php on line 38
