### ISSUE TITLE
New client is missing a webhook event service

### ISSUE THREAD

**Issue by chungryan** [stripe/stripe-php#955]
Would be great to have a webhook event service from the client to verify the signature

Currently can't do the following
```
$client = new Stripe\StripeClient($apiKey);
Webhook::constructEvent($payload, $signature, $this->signingSecret);
```
As this still requires the legacy way of doing things

So it doesn't seem I have any choice but to do
```
$client = new Stripe\StripeClient($apiKey);
Stripe::setApiKey($client->getApiKey());
$this->client->checkout->sessions->create([...]);
Webhook::constructEvent($payload, $signature, $this->signingSecret);
```

**Comment by remi-stripe** [comment]
@chungryan That part is expected because the client/service infrastructure is here for the API layer itself when you hit our API. The `constructEvent()` method is just an internal helper method but it's separate from the API so it will stay separate from this. You don't have to initialize the API key for that call to work so you can just call it as you would any static method!

**Comment by chungryan** [comment]
Indeed @remi-stripe 
Some other part of the code was still using the legacy client and I just quickly jumped on the conclusion that it was because of the webhook signature check. duh
Thanks
