### ISSUE TITLE
How to validate keys?

### ISSUE THREAD

**Issue by shmidtelson** [stripe/stripe-php#966]
I want to validate keys. But public_key i can validate only from JS.

I find solution for php lang.
For example: 
`$session->validatePublicKey('') and $session->validateSecretkeys()`

**Comment by remi-stripe** [comment]
@shmidtelson I'm not sure I follow which keys you want to validate exactly. Is this because you're building a plugin where someone copy-pastes an API key? We don't really have a way to do this server-side but what you can do is try to make a request with the key such as fetching a customer id for example and based on the error you'd know if the key is valid or not.

For example if you try to retrieve the customer cus_A with the key `fake_key` you get:
```
$ curl https://api.stripe.com/v1/customers/cus_A -u fake_key:
{
  "error": {
    "message": "Invalid API Key provided: fake_key",
    "type": "invalid_request_error"
  }
}
```

On the other hand, if you try to retrieve a customer cus_A with a real Publishable key, you get
```
$ curl https://api.stripe.com/v1/customers/cus_A -u pk_test_oVvdfHELwhPrzvkjRLN39OW4:
{
  "error": {
    "code": "secret_key_required",
    "doc_url": "https://stripe.com/docs/error-codes/secret-key-required",
    "message": "This API call cannot be made with a publishable API key. Please use a secret API key. You can find a list of your API keys at https://dashboard.stripe.com/account/apikeys.",
    "type": "invalid_request_error"
  }
}
```

So that would be enough for you to differentiate a Publishable key that is valid from one that isn't.

Hope this helps!

**Comment by shmidtelson** [comment]
@remi-stripe you're the best! Thanks!
