### ISSUE TITLE
Notice: Undefined property: Stripe\Service\CoreServiceFactory::$cards

### ISSUE THREAD

**Issue by kenned01** [stripe/stripe-php#969]
I'm facing this problem when I tried to implement any method for The (account) card object.
I can't create a card for a custom account, 
I can't get any card from any account

Notice: Undefined property: Stripe\Service\CoreServiceFactory::$cards
Fatal error: Uncaught Error: Call to a member function all() on null

and I'm doing exactly what is in the documentation 

$stripe = new \Stripe\StripeClient(
		SECRET_KEY_STRIPE
);

$stripe->cards->all(
		$account,
		['object' => 'card']
)

**Comment by paulasjes-stripe** [comment]
This is because you are calling a resource that doesn't exist. I'm guessing that you're trying to list all cards/PaymentMethods on an account, however cards and PaymentMethods exist on the customer level: https://stripe.com/docs/api/cards/list?lang=php

To list all Cards/PaymentMethods on an account, you'd have to first retrieve a list of all customers on an account and then list their PaymentMethods separately.

If instead you're using Stripe Issuing and you want to retrieve all generated virtual cards, then you'd use this endpoint instead: https://stripe.com/docs/api/issuing/cards/list?lang=php

```
$cards = $stripe->issuing->cards->all(['limit' => 3]);
```

For connected accounts you'd do the same as above but pass in the `Stripe-Account` header to indicate the account you wish to perform the action on:

```
$cards = $stripe->issuing->cards->all(
  ['limit' => 3],
  ['stripe_account' => 'acct_123']
);
```

I'm closing this as this we reserve Github issues for problems/bugs with the library, if you're still having problems I recommend reaching out to Stripe support directly: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
Adding a bit more context here: There is no client/service for the `Card` resource as this resource is under a Customer or an Account. Instead, you are expected to go through the parent Customer or Account. The code should look like this:

```
$stripe = new \Stripe\StripeClient(
		SECRET_KEY_STRIPE
);

$stripe->accounts->allExternalAccounts(
		$account,
		['object' => 'card']
)
```

I'll also make sure we get our docs fixed since they are incorrect
