### ISSUE TITLE
Console error regarding secret key while configure js

### ISSUE THREAD

**Issue by Nayan20** [stripe/stripe-php#976]
Hello,

Can any one help to check this issue.

(index):3 Uncaught Error: You are using a secret key with Stripe.js, instead of the publishable one. For more info, see https://stripe.com/docs/stripe.js
    at Function.b.validateKey ((index):3)
    at Function.b.create ((index):2)
    at Function.c.createToken ((index):2)
    at HTMLButtonElement.<anonymous> (common.js:513)
    at HTMLButtonElement.dispatch (jquery-2.2.3.min.js:3)
    at HTMLButtonElement.r.handle (jquery-2.2.3.min.js:3)

![image](https://user-images.githubusercontent.com/17044849/87908897-dc601680-ca84-11ea-8003-68e6472ef5b7.png)

**Comment by paulasjes-stripe** [comment]
Hi there, closing this as it isn't a problem with the stripe-php library. If you're having problems with your Stripe integration that aren't specific to this library, please contact Stripe support at https://support.stripe.com/contact

To unblock you, you are attempting to use your secret key (sk_test_123) instead of your publishable key (pk_test_123) when you initialize Stripe.js in your frontend code. The secret key must only be used on the server as it's extremely sensitive. If you use your publishable key (which you can find at https://dashboard.stripe.com/test/apikeys) you shouldn't get that error.

**Comment by Nayan20** [comment]
ok thanks 

let me check it..
