### ISSUE TITLE
Define possible properties of `StripeObject`

### ISSUE THREAD

**Issue by ThomasLandauer** [stripe/stripe-php#978]
This is somewhat related to https://github.com/stripe/stripe-php/issues/970

It looks like you're using [`StripeObject`](https://github.com/stripe/stripe-php/blob/master/lib/StripeObject.php) as a catch-all class for any unknown/undetermined result.

When running phpstan, I'm getting a bunch of errors, all related to `StripeObject`:

>   126    Access to an undefined property Stripe\StripeObject::$url.         
  218    Access to an undefined property Stripe\StripeObject::$object.      
  396    Access to an undefined property Stripe\StripeObject::$brand.       
  396    Access to an undefined property Stripe\StripeObject::$country.     
  396    Access to an undefined property Stripe\StripeObject::$funding. 

* Context of ine 126:
  ```php
  $source = Source::create([...]);
  $redirect = $source->redirect;
  return $redirect->url;
  ```
* Context of Line 218:
  ```php
  $event = Webhook::constructEvent(...);
  $object = $event->data;
  return $object->object;

* Context of Line 396:
  ```php
  $paymentIntent = PaymentIntent::retrieve(['id' => ..., 'expand' => ['payment_method.card']]);
  $card = $paymentIntent->payment_method->card;
  return $card->brand . ' ' . $card->funding . ' ' . $card->country;
  ```

stripe/stripe-php v7.39.0

**Comment by YOzaz** [comment]
Confirmed, last release which doesn't have this is v7.21.0:
https://github.com/stripe/stripe-php/compare/v7.21.0...v7.22.0

**Comment by richardm-stripe** [comment]
Hi @ThomasLandauer. We fall back to `StripeObject` when we don't have a more specific type that we can use - we are working on reducing the number of places where this occurs. However, I don't think think it makes sense to add all possible properties onto `StripeObject`, `StripeObject` is supposed to represent what every object in the Stripe API has in common if it represented the union of possible properties, instead of the intersection, this would mean thousands of property annotations. 

My recommendation is that, when you have more specific type information than is provided by the PHPDoc annotations, you should use `@phpstan-ignore-line`.

We could consider using just `mixed` as a fallback instead of `StripeObject`. This would suppress the errors you are seeing. However, I don't think this is in the spirit of type-safety, as PHPStan will just let you do whatever. When our type information is incomplete, I think it is better that we be conservative about the types we provide and let the user explicitly opt out of type-safety with `@phpstan-ignore-line`.

I'm going to close this ticket, as we don't intend to add more properties to `StripeObject` itself, but feel free to continue discussing.

**Comment by ThomasLandauer** [comment]
Looks like implemented by https://github.com/stripe/stripe-php/pull/1837
