### ISSUE TITLE
Bancontact, Giropay, iDeal, ...  incompatible with Stripe Connect

### ISSUE THREAD

**Issue by Greelings** [stripe/stripe-php#979]
We have completed the integration of the Bancontact, Giropay and iDeal payment methods.
It works perfectly well in test mode, however **in live mode** your server returns a 500 error when we try to retrieve the client_secret :

```
\Stripe\Stripe::setApiKey($secret_key);
$response = \Stripe\PaymentIntent::create([
    'amount' => 220,
    'currency' => 'eur',
    'payment_method_types' => ['giropay'],
    'statement_descriptor' => 'Au Bout Du Monde',
    'application_fee_amount' => round(220 * 1.9 / 100),
    ], ['stripe_account' => acct_abcde123456]);
echo $response->client_secret; // Error 500
```

After several tries, we noticed that the problem comes from Stripe Connect combined with the use of a payment method other than card.
For example, this works :

```
\Stripe\Stripe::setApiKey($secret_key);
$response = \Stripe\PaymentIntent::create([
    'amount' => 220,
    'currency' => 'eur',
    'payment_method_types' => ['giropay'],
    'statement_descriptor' => 'Au Bout Du Monde',
    ]);
echo $response->client_secret; // OK
```

And that works too :

```
\Stripe\Stripe::setApiKey($secret_key);
$response = \Stripe\PaymentIntent::create([
    'amount' => 220,
    'currency' => 'eur',
    'payment_method_types' => ['card'],
    'statement_descriptor' => 'Au Bout Du Monde',
    'application_fee_amount' => round(220 * 1.9 / 100),
    ], ['stripe_account' => acct_abcde123456]);
echo $response->client_secret; // OK
```

So the question is, are bancontact, giropay, ideal, ... incompatible with Stripe Connect?

**Comment by remi-stripe** [comment]
@Greelings Is your code crashing when you try to access `client_secret` because it's null, or is it crashing because the PaymentIntent creation itself is raising an exception and your code is not catching those exceptions?

My guess is that it's the latter and if you catch exceptions as documented in https://stripe.com/docs/api/errors then you should be able to see the exact error that is being returned via the API.

I also looked into our logs and I found a handful of requests today for a PaymentIntent creation with Bancontact as the payment method type and the request succeeded and returned a `client_secret` as expected.

I don't think this could be a bug with the stripe-php library so I would recommend reaching out to our support team directly instead https://support.stripe.com/contact and they can help you debug this once you provide more specific details about the error and which account this is failing on.
