### ISSUE TITLE
Uncaught (Status 400) (Request req_xxxxxxxxxxxx) This value must be greater than or equal to 1.   thrown in /path/vendor/stripe/stripe-php/lib/Exception/ApiErrorException.php on line 38

### ISSUE THREAD

**Issue by jacobnoah** [stripe/stripe-php#982]
Has anyone ever gotten this error before? This was all working earlier today and now when I am running it I see a 500 error in Chrome and in Terminal I am seeing the Uncaught (Status 400) (Request req_xxxxxxxxxxxx) This value must be greater than or equal to 1.   thrown in /path/vendor/stripe/stripe-php/lib/Exception/ApiErrorException.php on line 38. I am wondering if anyone knows how to solve this problem. (Also I checked and the amount property is getting added properly and is greater than 1).

**Comment by remi-stripe** [comment]
@jacobnoah This error means that one of your parameters is not set properly. The error returned should tell you the exact parameter and with the `req_123456` you can view that log in the Dashboard and read the exact message we gave you. Otherwise make sure to catch the exception as documented in https://stripe.com/docs/api/errors to dump the whole error.

I'm going to close this out since it wouldn't be a bug with the library itself, it's an issue with your code and likely passing an initialized variable or one that is set to 0. Please don't hesitate to follow up with our support team instead: https://support.stripe.com/contact
