### ISSUE TITLE
Uncaught Error: Class 'Stripe\Review' not found in ..../stripe-php/lib/Util/Util.php:46

### ISSUE THREAD

**Issue by Lipton1** [stripe/stripe-php#985]
Hi,

trying to retrieve customer information with stripe-php version 7.45.0 leads to following error (with shortened URLs):

```
Uncaught Error: Class 'Stripe\Review' not found in /home/www/....../stripe-php/lib/Util/Util.php:46
Stack trace:
#0 /home/www/....../stripe-php/lib/BaseStripeClient.php(136): Stripe\Util\Util::convertToStripeObject(Array, Object(Stripe\Util\RequestOptions))
#1 /home/www/....../stripe-php/lib/Service/AbstractService.php(59): Stripe\BaseStripeClient-&gt;request('get', '/v1/customers/c...', Array, Object(Stripe\Util\RequestOptions))
#2 /home/www/....../stripe-php/lib/Service/CustomerService.php(221): Stripe\Service\AbstractService-&gt;request('get', '/v1/customers/c...', Array, NULL)
#3 /home/www/....../stripetest.php(58): Stripe\Service\CustomerService-&gt;retrieve('cus_Dx...', Array)
```

On the stripe-site the request is received and handled with no issues.

Code looks like this:

```
require 'stripe-php/init.php';
$stripe = new \Stripe\StripeClient('sk_test_...');
$stripe->customers->retrieve('cus_Dx...J', []);
```

**Comment by ctrudeau-stripe** [comment]
Hello @Lipton1,  thanks for the report!

We tried to reproduce this on our setups but were unable to and are unsure whether this represents a real bug in the `stripe-php` or if it is something unique to your particular setup.

Would you be willing to provide us with the request_id of one of the requests that is triggering this failure? And since this may likely be an issue with your particular set up, we recommend reaching out to Stripe support directly: https://support.stripe.com/contact, and they can assist you more interactively.

**Comment by richardm-stripe** [comment]
Closed for inactivity -- we hope you were able to resolve your problem. If not feel free to reopen with additional information.
