### ISSUE TITLE
New "update available" widget persists after upgrade to v.7.46.1

### ISSUE THREAD

**Issue by hondaman900** [stripe/stripe-php#993]
Recently (within the last week) my app started showing an "update available" message, top right of the card processing page (when the card details entry modal was in effect). So I upgraded stripe-php from v.5.6 to v.7.46.1 via composer but the message persists. Expectation is that the message is resolved with the new version.

I'm running Laravel 6.18.35 and PHP 7.4.8 on a Nginx server.

**Comment by remi-stripe** [comment]
@hondaman900 Github issues should be limited to bugs with the stripe-php library itself so I'm going to close this out and I would recommend discussing this with our support team directly instead: https://support.stripe.com/contact

To help unblock you though, what you are describing seems to happen client-side in the UI which wouldn't be controlled by your PHP code itself. I'm unclear what you are referring to exactly but I think might be because you are using the Legacy Checkout integration (the modal for card details on your page) which we deprecated over a year ago already. If so, you should look at the new version of Checkout instead: http://stripe.com/checkout

I hope this helps but otherwise you should talk to our support team and they can clarify this directly with you!
