### ISSUE TITLE
Checkout session Error

### ISSUE THREAD

**Issue by markomeje** [stripe/stripe-php#995]
I'm always getting this error "Something went wrong
The specified Checkout Session could not be found. This error is usually caused by using the wrong API key. Please make sure the API keys used to initialize Stripe.js and create the Checkout Session are test mode keys from the same account." when i use the php sdk version 7.46 with check checkout session api. But if i use the charge customer api which allows the payment on my website instead of a redirect, it works. But i want a redirect to stripe checkout session page. The api key error as specified by stripe is confusing because that's the same api key i'll use to process the charge customer api and it will work perfectly. I'm on php 7.4.8. Any help is greatly appreciated.

**Comment by remi-stripe** [comment]
@markomeje This wouldn't be an issue with stripe-php. Instead, you have an issue with the API keys you are using at the moment. It could be due to multiple things such as whether you're using Connect, whether you hardcoded the wrong publishable key client-side, etc. Unfortunately it wouldn't be easy to debug this on Github and issues here should be limited to bugs with the library itself.

My advice here is to triple check your API keys, both the one server-side called the Secret API key (sk_test_123) and the one client-side called the Publishable API key (pk_test_123456) and make sure they match what you see in your Dashboard.

Otherwise, I'd recommend that you reach out to our support team, share example objects (such as the Session id cs_test_123) and a URL where to view your code so that they can help you debug this

**Comment by varunsidwani** [comment]
hey @markomeje  were you able to fix this error?? I'm getting the exact same error, can you please help me solve this??

**Comment by yogeshvishnole** [comment]
I am also getting same error , can above people if they solve problem , give solution here.

**Comment by remi-stripe** [comment]
@yogeshvishnole Please contact our support team for help instead: https://support.stripe.com/contact
