### ISSUE TITLE
Is it impossible to update the price through API?

### ISSUE THREAD

**Issue by estevaob** [stripe/stripe-php#999]
How can I update the price though API? It doesn't recognize "unit_amount"

**Comment by remi-stripe** [comment]
@estevaob Thanks for reaching out! In our API, Price is considered immutable and you should simply create a new Price if you want to change your pricing and start using the new Price for new customers.

I'm going to close this ask as it's not an issue with our library itself but if you have any follow-up questions don't hesitate to ask our support team: https://support.stripe.com/contact

**Comment by andymnewhouse** [comment]
But then why can you update it through the dashboard?

**Comment by remi-stripe** [comment]
@andymnewhouse Mostly because it's a UI-based flow we fully own where we can add strict restrictions with a good UI/helper to allow you to do this in really specific cases. 
While I've flagged this internally for further discussion, this is not something that we are going to change in the public API for now. I'd recommend reaching out to our support team if you have any follow up questions on that subject: https://support.stripe.com/contact
